[workspace]
members = [
    "quillmark-core",
    "quillmark",
    "quillmark-typst",
    "quillmark-fixtures"
]
resolver = "2"

[workspace.dependencies]
thiserror = "1.0"
quillmark-fixtures = { path = "quillmark-fixtures" }
