[workspace]
members = [
    "quillmark-core",
    "quillmark",
    "quillmark-typst"
]
resolver = "2"

[workspace.dependencies]
thiserror = "1.0"

[workspace.examples]
hello-quill = { path = "examples/hello-quill" }