# Drive bumps + tagging with cargo-release; publishing happens in CI after commit to main.
# Invoke locally like:
#   cargo release <patch|minor|major> --execute --workspace

# Only release from main
allow-branch = ["main"]

# Bump + tag + push, but DO NOT publish here
publish = false
tag = true
push = true
push-remote = "origin"

# Versioning + commits/tags
dependent-version = "upgrade"              # auto-update intra-workspace dependency versions
consolidate-commits = true                 # single bump commit for the workspace
pre-release-commit-message = "chore: release {{version}}"
tag-name = "v{{version}}"
tag-message = "Release {{version}}"

# Safety / defaults
verify = true
sign-commit = false
sign-tag = false