[package]
name = "quillmark-fixtures"
version = "0.1.0"
edition = "2021"
description = "Test fixtures and utilities for Quillmark"
license = "MIT"

[dependencies]
quillmark = { workspace = true }
quillmark-typst = { workspace = true }