[package]
name = "quillmark-fixtures"
version.workspace = true
edition.workspace = true
description = "Test fixtures and utilities for Quillmark"
license = "MIT"

[dependencies]
quillmark = { workspace = true }
quillmark-typst = { workspace = true }