[package]
name = "quillmark-fixtures"
version = "0.1.0"
edition = "2021"
description = "Test fixtures and utilities for QuillMark examples (dev-only)"

[dependencies]
thiserror = { workspace = true }
