[Quill]
name = "taro"
backend = "typst"
glue_file = "glue.typ"
example_file = "taro.md"
description = "Taro template for documents"

[fields]
author = {description = "Author of document", required = true}
ice_cream = {description = "favorite ice cream flavor"}
title = {description = "title of document", required = true}