[package]
name = "quillmark-typst"
version.workspace = true
edition.workspace = true
description = "Typst backend for Quillmark"
license = "Apache-2.0"

[dependencies]
fontdb = "0.21.0"
pulldown-cmark = "0.13.0"
quillmark-core = { path = "../quillmark-core" }
serde_json.workspace = true
time = { version = "0.3.44", features = ["formatting", "parsing"] }
toml.workspace = true
typst = "0.13.1"
typst-kit = "0.13.1"
typst-pdf = "0.13.1"
typst-svg = "0.13.1"
dirs = "6.0"

[dev-dependencies]
tempfile = { workspace = true }

