[package]
name = "quillmark-typst"
version = "0.1.0"
edition = "2021"
description = "Typst backend for QuillMark"
license = "MIT"

[dependencies]
pulldown-cmark = "0.13.0"
quillmark-core = { path = "../quillmark-core" }
serde_json.workspace = true
time = { version = "0.3.44", features = ["formatting", "parsing"] }
toml.workspace = true
