[package]
name = "quillmark-typst"
version = "0.1.0"
edition = "2021"
description = "Typst backend for QuillMark"
license = "MIT"

[dependencies]
quillmark-core = { path = "../quillmark-core" }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
chrono = { workspace = true }
typst = { workspace = true }
typst-pdf = { workspace = true }