[package]
name = "quillmark-typst"
version = "0.1.0"
edition = "2021"
description = "Typst backend for quillmark using pulldown-cmark and Typst"
license = "MIT"
repository = "https://github.com/nibsbin/quillmark"

[dependencies]
quillmark-core = { path = "../quillmark-core" }
thiserror = { workspace = true }
# typst = { version = "0.13.1" }