//! Content → Typst-markup emitter that records a per-segment source map.
//!
//! The one place a source map can be produced: it both lowers the content and
//! knows the resulting byte layout. Walks a
//! [`Content`](quillmark_content::Content) to Typst markup, never re-parsing
//! markdown, recording per segment (a maximal run of lines joined by
//! [`Line::continues`](quillmark_content::model::Line::continues) — one
//! paragraph, heading, code fence, or island line) the generated byte window
//! plus one `(content ↔ generated)` pair per text run. Marks lower through a
//! boundary sweep with close-and-reopen at overlaps: Peritext free overlap →
//! properly nested Typst.
//!
//! **Line-anchored text.** [`escape_markup`](crate::emit::escape_markup)
//! neutralizes inline markup but is
//! position-blind; Typst's heading `=`, list `-`/`+`/`N.`, and term `/` are only
//! special as the first token of a markup line, and each fires on a space after it
//! or on the line ending there. Text opening with one there would render as that
//! block — a lone `/` as a term list whose colon is missing, which is a parse
//! error — so the emitter prefixes a single `\` (`opens_line_anchor`).
//!
//! That position is Typst's `at_start`, and it is four places: column 0
//! with indentation ahead of it not counting, a list item's body head, the head
//! of every content block `[…]` the emitter opens (each wrap, each table cell),
//! and the run of spaces or tabs behind any of them, which Typst reads as trivia.
//! A heading's body is none of them. `at_line_anchor` answers the first two,
//! `sweep_marks` carries the third, `emit_run` the fourth. Styling-only:
//! `#`, `[`, `$` are already escaped, so this is no code-execution vector.
//!
//! **Expression tails.** The same `\` guards the other direction. Typst reads a
//! `(` directly after a `#…` expression as that call's arguments, a `.` before
//! an identifier as a field access, and a `;` as the expression's terminator, so
//! the text behind an emitted `#raw(…)` or a wrap's `]` would reach it as code
//! — or, for the `;`, vanish (`continues_expr`).
//!
//! **Seams.** And a third time, where the emitter writes nothing between two
//! runs. Escaping is per run, so a multi-character rule sees one side of such a
//! join at a time and the coupling straddling it escapes neither
//! (`couples_across`).
//!
//! **The 2→4 escape coupling.** Each run records only its `(content, generated)`
//! pair; per-char spans are *recomputed* by a scan treating `//`→`\/\/` as a
//! 2-char/4-byte cluster and every other char as its own. The `escape_tripwire`
//! tests pin that scan against [`escape_markup`](crate::emit::escape_markup) /
//! [`escape_string`](crate::emit::escape_string) byte-for-byte, so an escape-rule change fails loud.

use quillmark_core::error::MAX_NESTING_DEPTH;
use quillmark_content::island::KnownIslandType;
use quillmark_content::model::{Container, LineKind, Mark, MarkKind, Content, Normalized, ISLAND_SLOT};
use quillmark_content::normalize::is_line_separator;
use std::ops::Range;

/// Does Typst's lexer read `c` as a newline where the emitter writes document
/// text? Every character of its `is_newline` set but `\n`, which the emitter
/// writes itself as a line boundary. `Content::validate` rejects all of them, so
/// one reaches here only from a content the ingress never made.
fn reads_as_newline(c: char) -> bool {
    c == '\r' || is_line_separator(c)
}

/// Neutralizes every markup-special character, so document text cannot inject
/// markup, references (`@`), or comments (`//`).
///
/// Typst's lexer also substitutes a codepoint for `~` (a non-breaking space),
/// `--`/`---` (en/em dash), `-?` (an invisible soft hyphen), `-` before a number
/// (a minus sign), and `...` (an ellipsis). Escaping a multi-character one at
/// its head is enough: what it leaves behind is too short to re-form it.
///
/// A mid-word `3-5` is absorbed into Typst's running text node and substitutes
/// nothing, so escaping every `-` before a number takes one more than the page
/// needs. Reading far enough to tell would tie this function to a tokenization
/// the lexer owns.
///
/// Every character Typst reads as a newline but `\n` lowers to a space, the
/// content ingress's own rule. No escape neutralizes one — a `\` before
/// whitespace is Typst's linebreak — and each reopens `at_start`, so the text
/// behind it would parse as a heading, list or term marker. The space it becomes
/// is trivia to the emitter, which holds the line-anchor guard open behind it.
///
/// `'` and `"` pass through. Smart quotes are an element with a set rule, so a
/// quill chooses with `#set smartquote(enabled: false)`; escaping them here
/// would settle that for every quill with no way back.
pub fn escape_markup(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(c) = rest.chars().next() {
        rest = &rest[c.len_utf8()..];
        match c {
            // Four bytes for two content chars, which `gen_cluster` inverts
            // as one cluster.
            '/' if rest.starts_with('/') => {
                out.push_str(r"\/\/");
                rest = &rest[1..];
            }
            '-' if rest.starts_with(['-', '?'])
                || rest.chars().next().is_some_and(char::is_numeric) =>
            {
                out.push_str(r"\-")
            }
            '.' if rest.starts_with("..") => out.push_str(r"\."),
            // One char to one byte, which `gen_cluster` reads back as a plain
            // cluster.
            c if reads_as_newline(c) => out.push(' '),
            '\\' | '~' | '*' | '_' | '`' | '#' | '[' | ']' | '{' | '}' | '$' | '<' | '>' | '@' => {
                out.push('\\');
                out.push(c);
            }
            _ => out.push(c),
        }
    }
    out
}

/// Inside a Typst string literal only `"` and `\` are structural; newlines and
/// tabs get their escape, other ASCII controls become `\u{..}`.
pub fn escape_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => {
                use std::fmt::Write as _;
                let _ = write!(out, "\\u{{{:x}}}", c as u32);
            }
            c => out.push(c),
        }
    }
    out
}

/// Does `s` open a line-anchored Typst block: heading `= `, bullet `- `, enum
/// `+ `/`N. `, term `/ `? The marker token is followed by whitespace or ends the
/// run, which is Typst's own test (`space_or_end`), so `=foo`, `-5`, `and/or`,
/// `1.item` are inert and a paragraph holding one bare `/` is a slash rather
/// than a term list whose colon is missing. The run ends at a mark, an island,
/// or the line, and everything the emitter opens there starts `#`, so the end
/// case escapes one line-final marker and never a token mid-line. `s` starts at
/// the marker: [`emit_run`] cuts a run's leading trivia away, so a space here is
/// prose rather than an indented marker.
fn opens_line_anchor(s: &str) -> bool {
    let b = s.as_bytes();
    let clear = |n: usize| s[n..].chars().next().is_none_or(char::is_whitespace);
    match b.first().copied() {
        Some(b'=') => clear(b.iter().take_while(|&&c| c == b'=').count()),
        Some(b'-') | Some(b'+') | Some(b'/') => clear(1),
        Some(c) if c.is_ascii_digit() => {
            let n = b.iter().take_while(|&&c| c.is_ascii_digit()).count();
            b.get(n) == Some(&b'.') && clear(n + 1)
        }
        _ => false,
    }
}

/// Does `s` continue the `#…` expression written before it? Typst reads a `(`
/// directly after one as that call's arguments and a `.` before an identifier
/// as a field access, either swallowing document text into code: a `` `x` ``
/// followed by `(y)` emits `#raw("x")(y)`, a call on content. A `;` directly
/// after one terminates it, and the character renders as nothing. `[` needs no
/// rule, [`escape_markup`] having escaped it already, and trivia between the two
/// ends the expression on its own.
fn continues_expr(s: &str) -> bool {
    let mut c = s.chars();
    match c.next() {
        Some('(') | Some(';') => true,
        Some('.') => c.next().is_some_and(typst::syntax::is_id_start),
        _ => false,
    }
}

/// Do the characters either side of a seam form a Typst coupling? `prev` is the
/// character behind it, `s` the text ahead. An island this build renders as
/// nothing lets two runs abut that the content keeps apart, and [`escape_markup`]
/// sees one side at a time: `a/`, that island, `/b` writes `a//b`, a comment
/// that eats the rest of the line. Conservative on `...`, whose third dot can
/// sit either side.
fn couples_across(prev: Option<char>, s: &str) -> bool {
    match (prev, s.chars().next()) {
        (Some('/'), Some('/')) | (Some('.'), Some('.')) => true,
        (Some('-'), Some(c)) => c == '-' || c == '?' || c.is_numeric(),
        _ => false,
    }
}

/// What the emitter last wrote, which decides the guard the next text run needs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Tail {
    /// Typst's `at_start`: a heading, list or term marker is live here.
    Anchor,
    /// The end of a `#…` expression, which [`continues_expr`] can extend.
    Expr,
    /// Ink, which ends both.
    Text,
    /// Ink, then something that emitted no bytes: the text ahead abuts the text
    /// behind ([`couples_across`]).
    Seam,
}

/// The escape discipline a text run was generated under: which scan inverts its
/// per-char spans. `//`→`\/\/` couples 2 content chars to 4 generated bytes
/// under both; every other rule differs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EscapeCtx {
    /// [`escape_markup`]: Typst markup body (`\*`, `\#`, `\/\/`, …).
    Markup,
    /// [`escape_string`]: inside a `"…"` literal (`\"`, `\\`, `\n`, `\/\/` no-op).
    StringLit,
}

/// `(content_chars, byte_len)` for the cluster at byte `i` of `generated`. Reads
/// the escape structure back off the generated text: a lone `\/` only ever
/// arises from the `//` coupling, `\X` escapes are self-delimiting, and `\u{..}`
/// closes on its brace, so the scan needs no stored per-char table.
fn gen_cluster(generated: &str, i: usize, ctx: EscapeCtx) -> (usize, usize) {
    let rest = &generated[i..];
    match ctx {
        EscapeCtx::Markup => {
            // `\/\/`, the `//` coupling: two content chars, four bytes, one cluster.
            if rest.as_bytes().starts_with(br"\/\/") {
                return (2, 4);
            }
            let mut chars = rest.chars();
            let c = chars.next().expect("i is a char boundary within generated");
            if c == '\\' {
                // A `\X` escape: backslash plus one (ASCII, 1-byte) escaped char.
                (1, 1 + chars.next().map(char::len_utf8).unwrap_or(0))
            } else {
                (1, c.len_utf8())
            }
        }
        EscapeCtx::StringLit => {
            let mut chars = rest.chars();
            let c = chars.next().expect("i is a char boundary within generated");
            if c == '\\' {
                match chars.next() {
                    // `\u{..}` control escape: consume through the closing brace.
                    Some('u') => (1, rest.find('}').map(|b| b + 1).unwrap_or(rest.len())),
                    // `\n`/`\r`/`\t`/`\\`/`\"`: two bytes.
                    Some(c2) => (1, 1 + c2.len_utf8()),
                    None => (1, 1),
                }
            } else {
                (1, c.len_utf8())
            }
        }
    }
}

/// A generated byte offset (into one run's slice) → content USV offset relative
/// to the run's content start. A `target` inside a multi-byte cluster floors to
/// that cluster's first content char, matching how `glyph.span.1` is computed
/// once per shaped cluster. The floor is per Unicode scalar value, not per
/// grapheme, so a caret can resolve between a base char and a combining mark.
pub(crate) fn invert_gen_offset(generated: &str, ctx: EscapeCtx, target: usize) -> usize {
    let (mut byte, mut content) = (0usize, 0usize);
    while byte < generated.len() {
        let (cc, bl) = gen_cluster(generated, byte, ctx);
        if target < byte + bl {
            return content;
        }
        byte += bl;
        content += cc;
    }
    content
}

/// The inverse of [`invert_gen_offset`]. An offset landing inside the `//`
/// coupling maps past the whole cluster: the coupling is atomic.
pub(crate) fn forward_content_offset(generated: &str, ctx: EscapeCtx, content_off: usize) -> usize {
    let (mut byte, mut content) = (0usize, 0usize);
    while byte < generated.len() {
        if content >= content_off {
            return byte;
        }
        let (cc, bl) = gen_cluster(generated, byte, ctx);
        content += cc;
        byte += bl;
    }
    byte
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SegmentMap {
    /// USV (Unicode scalar value) range.
    pub content: Range<usize>,
    /// Byte range in [`Emission::markup`].
    pub generated: Range<usize>,
    /// One `(content USV range, generated byte range, escape context)` per text
    /// run. Structural bytes fall between runs, covered by [`Self::generated`]
    /// but no run.
    pub runs: Vec<(Range<usize>, Range<usize>, EscapeCtx)>,
}

#[derive(Debug, Clone)]
pub struct Emission {
    pub markup: String,
    /// One entry per emitted segment, in generation order.
    pub segments: Vec<SegmentMap>,
    /// Image islands this emission drew nothing for. Counted off `islands`
    /// rather than off the slots, so an image counts wherever it sits.
    pub declined_images: usize,
}

impl Emission {
    /// A syntax error in emitted markup is a lowering bug, never a document's.
    /// Typst's parser is the only faithful judge of its own grammar, so debug
    /// builds run it over every emission.
    fn new(rt: &Content, markup: String, segments: Vec<SegmentMap>) -> Self {
        debug_assert!(
            !typst::syntax::parse(&markup).diagnosis().errors,
            "emitted markup does not parse: {:?}\n{markup:?}",
            typst::syntax::parse(&markup).errors_and_warnings().0,
        );
        Emission {
            markup,
            segments,
            declined_images: rt
                .islands
                .iter()
                .filter(|i| KnownIslandType::parse(&i.island_type) == Some(KnownIslandType::Image))
                .count(),
        }
    }
}

/// What stops codegen mid-walk. Each carries the diagnostic code the render
/// error reports, so folding a check into the walk does not relabel it.
#[derive(Debug, thiserror::Error)]
pub enum EmitError {
    /// Import already caps nesting at [`MAX_NESTING_DEPTH`], so this fires only
    /// on a hand-built content that skipped that guard.
    #[error("Nesting too deep: {depth} levels (max: {max} levels)")]
    NestingTooDeep { depth: usize, max: usize },
    /// A non-blank date the shared parsers reject. Only a direct `apply` can
    /// deliver one: coercion parses the same way.
    #[error("invalid date in field {field:?}: {value:?} is not a recognized date")]
    InvalidDate { field: String, value: String },
}

impl EmitError {
    pub fn code(&self) -> &'static str {
        match self {
            EmitError::NestingTooDeep { .. } => "typst::emit",
            EmitError::InvalidDate { .. } => "backend::invalid_date",
        }
    }
}

pub fn emit_content(rt: &Normalized) -> Result<Emission, EmitError> {
    let max_depth = rt
        .lines
        .iter()
        .map(|l| l.containers.len())
        .max()
        .unwrap_or(0);
    if max_depth > MAX_NESTING_DEPTH {
        return Err(EmitError::NestingTooDeep {
            depth: max_depth,
            max: MAX_NESTING_DEPTH,
        });
    }
    let mut e = Emit::new(rt);
    let n = rt.lines.len();
    e.emit_block_level(0..n, 0);
    Ok(Emission::new(rt, e.out, e.segments))
}

/// Lower an [`is_inline`] content to pure inline markup, omitting the block
/// terminator (`\n\n`, a `parbreak()`) so the field composes in an inline slot
/// without Typst's "parbreak may not occur inside of a paragraph" warning.
/// Anything not [`is_inline`] falls back to [`emit_content`].
///
/// [`is_inline`]: quillmark_content::Content::is_inline
pub(crate) fn emit_content_inline(rt: &Normalized) -> Result<Emission, EmitError> {
    if !rt.is_inline() {
        return emit_content(rt);
    }
    // `is_inline` guarantees depth 0, so `emit_content`'s nesting guard is moot.
    let mut e = Emit::new(rt);
    e.emit_segment(0..rt.lines.len());
    Ok(Emission::new(rt, e.out, e.segments))
}

struct Emit<'a> {
    rt: &'a Content,
    /// Content text as USV, so a `[start, end)` USV range slices in O(1).
    chars: Vec<char>,
    /// Per line: its `[start, end)` USV range (text only, excluding the `\n`
    /// separators, which sit at each non-last line's `end`).
    line_usv: Vec<(usize, usize)>,
    /// USV positions of every [`ISLAND_SLOT`] char, ascending, so an island
    /// slot maps to its island index by a binary search, not a content rescan.
    slot_offsets: Vec<usize>,
    out: String,
    segments: Vec<SegmentMap>,
    /// Whether `out` currently ends at a fresh line, tracked so block
    /// separators land consistently.
    end_newline: bool,
    /// The prefix every generated line opens with: two spaces per enclosing
    /// list item. Typst ends a list at a block written to column 0, so leaves
    /// and containers alike open through [`Self::open_line`].
    indent: String,
    /// Whether the next block opens where `out` already sits: a list item's
    /// body head, off its marker.
    head_inline: bool,
    /// How far [`Self::overlapping_marks`] has walked `rt.marks`.
    mark_cursor: usize,
}

impl<'a> Emit<'a> {
    fn new(rt: &'a Content) -> Self {
        let chars: Vec<char> = rt.text.chars().collect();
        // Per-line USV `[start, end)` from the shared segmentation (including
        // the malformed-content padding) so the two crates cannot drift.
        let line_usv: Vec<(usize, usize)> = quillmark_content::export::line_segments(rt)
            .iter()
            .map(|s| (s.start, s.end))
            .collect();
        let slot_offsets: Vec<usize> = chars
            .iter()
            .enumerate()
            .filter_map(|(i, &c)| (c == ISLAND_SLOT).then_some(i))
            .collect();
        Emit {
            rt,
            chars,
            line_usv,
            slot_offsets,
            out: String::new(),
            segments: Vec::new(),
            end_newline: true,
            indent: String::new(),
            head_inline: false,
            mark_cursor: 0,
        }
    }

    /// The marks that can overlap `[lo, hi)`, as a slice of `rt.marks`.
    ///
    /// Segments are emitted in ascending content order, so a mark ending at or
    /// before `lo` is behind every segment still to come and the cursor drops it
    /// for good; `normalize_marks` leaves marks ascending by `start`, so the
    /// first one starting at or after `hi` ends the slice. Both bounds are
    /// conservative — [`wraps_and_codes`] still clamps and discards — so the
    /// only effect is not rescanning the whole mark list per segment.
    fn overlapping_marks(&mut self, lo: usize, hi: usize) -> &'a [Mark] {
        let marks: &'a [Mark] = &self.rt.marks;
        while self.mark_cursor < marks.len() && marks[self.mark_cursor].end <= lo {
            self.mark_cursor += 1;
        }
        let rest = &marks[self.mark_cursor..];
        &rest[..rest.partition_point(|m| m.start < hi)]
    }

    /// Leaf blocks terminate with `\n\n`; lists and quotes carry their own
    /// whitespace. List *item* bodies use [`Self::emit_item_body`] instead.
    fn emit_block_level(&mut self, range: Range<usize>, depth: usize) {
        let mut i = range.start;
        while i < range.end {
            if let Some(j) = self.try_emit_container(range.clone(), depth, i) {
                i = j;
                continue;
            }
            let j = self.segment_end(range.clone(), depth, i);
            self.emit_leaf_terminated(i..j);
            i = j;
        }
    }

    /// `None` for a leaf, leaving the caller to emit it under its own
    /// discipline (top-level terminated vs list item body).
    fn try_emit_container(&mut self, range: Range<usize>, depth: usize, i: usize) -> Option<usize> {
        let rt = self.rt;
        // A leaf first: `runs` skips a line carrying no container at `depth`,
        // so without this the run *after* the leaf would swallow it.
        rt.lines[i].containers.get(depth)?;
        let run = quillmark_content::traverse::runs(&rt.lines, i..range.end, depth)
            .next()
            .expect("a line with a container at `depth` opens a run");
        let j = run.range.end;
        match run.container {
            Container::ListItem { ordered, start, .. } => {
                self.emit_list(i..j, depth, *ordered, *start);
                Some(j)
            }
            Container::Quote { .. } => {
                self.emit_quote(i..j, depth);
                Some(j)
            }
            // Open set: a container this build does not know is **transparent**,
            // its run lowers at the next depth with no wrapper markup, so the
            // blocks inside it render where they would without it. Consuming
            // the whole run here keeps its lines grouped as one block instead
            // of splitting them.
            _ => {
                self.emit_block_level(i..j, depth + 1);
                Some(j)
            }
        }
    }

    fn segment_end(&self, range: Range<usize>, depth: usize, i: usize) -> usize {
        quillmark_content::traverse::segment(&self.rt.lines, i..range.end, depth).end
    }

    /// Opens a block's line at [`Self::indent`], ending the current one if
    /// prose has reached it. A list item's body head is already such a
    /// position, so the first block there opens in place.
    fn open_line(&mut self) {
        if std::mem::take(&mut self.head_inline) {
            return;
        }
        if !self.end_newline {
            self.out.push('\n');
        }
        self.out.push_str(&self.indent);
        self.end_newline = true;
    }

    /// An empty paragraph emits nothing; every other block (an empty heading or
    /// code fence included) still renders.
    fn emit_leaf_terminated(&mut self, range: Range<usize>) {
        let first = &self.rt.lines[range.start];
        let (lo, _) = self.line_usv[range.start];
        let (_, hi) = self.line_usv[range.end - 1];
        if first.kind.projects_as_para() && lo == hi {
            return;
        }
        self.open_line();
        self.emit_segment(range);
        self.out.push_str("\n\n");
        self.end_newline = true;
    }

    /// The trailing `\n` goes on only when this is the outermost list.
    fn emit_list(&mut self, range: Range<usize>, depth: usize, ordered: bool, start: u64) {
        let outermost = !self.rt.lines[range.start].containers[..depth]
            .iter()
            .any(|c| matches!(c, Container::ListItem { .. }));
        let rt = self.rt;
        for item in quillmark_content::traverse::items(&rt.lines, range.clone(), depth) {
            let ordinal = match item.container {
                Container::ListItem { ordinal, .. } => *ordinal,
                _ => 0,
            };
            self.emit_item(item.range, depth, ordered, start, ordinal == 0);
        }
        if outermost {
            self.out.push('\n');
            self.end_newline = true;
        }
    }

    /// The marker is `- `, the explicit `N. ` on the first item of an ordered
    /// list starting off-1, or `+ ` (Typst auto-numbers `+` from that number).
    fn emit_item(
        &mut self,
        range: Range<usize>,
        depth: usize,
        ordered: bool,
        start: u64,
        first: bool,
    ) {
        self.open_line();
        if ordered {
            // Typst runs one counter across adjacent `+` items
            // (`typst-layout::lists` takes `item.number.unwrap_or(number)`), so
            // two adjacent lists would number 1 2 3 4. Stating the first item's
            // number resets it, which is the whole boundary in the projection.
            if first {
                self.out.push_str(&format!("{}. ", start));
            } else {
                self.out.push_str("+ ");
            }
        } else {
            self.out.push_str("- ");
        }
        self.end_newline = false;
        self.head_inline = true;
        self.indent.push_str("  ");
        self.emit_item_body(range, depth + 1);
        self.indent.truncate(self.indent.len() - 2);
        self.head_inline = false;
        if !self.end_newline {
            self.out.push('\n');
            self.end_newline = true;
        }
    }

    /// The first block flows straight off the marker; each later block is
    /// preceded by a blank line.
    fn emit_item_body(&mut self, range: Range<usize>, content_depth: usize) {
        let mut first_block = true;
        let mut i = range.start;
        while i < range.end {
            if !first_block {
                self.blank_line();
            }
            first_block = false;
            if let Some(j) = self.try_emit_container(range.clone(), content_depth, i) {
                i = j;
                continue;
            }
            let j = self.segment_end(range.clone(), content_depth, i);
            self.open_line();
            self.emit_segment(i..j);
            if !self.end_newline {
                self.out.push('\n');
                self.end_newline = true;
            }
            i = j;
        }
    }

    /// Separates two blocks of one list item, unless the block just emitted
    /// closed on a blank line of its own.
    fn blank_line(&mut self) {
        if !self.end_newline {
            self.out.push('\n');
            self.end_newline = true;
        }
        if !self.out.ends_with("\n\n") {
            self.out.push('\n');
        }
    }

    /// `#quote(block: true)[…]`: quotes render structurally, not flattened.
    fn emit_quote(&mut self, range: Range<usize>, depth: usize) {
        self.open_line();
        self.out.push_str("#quote(block: true)[\n");
        self.end_newline = true;
        self.emit_block_level(range, depth + 1);
        self.open_line();
        self.out.push(']');
        self.out.push_str("\n\n");
        self.end_newline = true;
    }

    /// Leaves `end_newline` false: the caller owns the terminator.
    fn emit_segment(&mut self, range: Range<usize>) {
        let kind = self.rt.lines[range.start].kind.clone();
        let (lo, _) = self.line_usv[range.start];
        let (_, hi) = self.line_usv[range.end - 1];
        // A code fence records its own window/runs.
        if let LineKind::Code { lang } = &kind {
            self.emit_code(range, lang.as_deref(), lo, hi);
            self.end_newline = false;
            return;
        }
        // `g0` opens the recorded window after any prefix.
        let (g0, runs) = match kind {
            LineKind::Heading { level } => {
                self.out.push_str(&"=".repeat(level as usize));
                self.out.push(' ');
                let g0 = self.out.len();
                (g0, self.emit_inline(lo, hi))
            }
            LineKind::Rule => {
                let g0 = self.out.len();
                self.out.push_str("#line(length: 100%)");
                (g0, Vec::new())
            }
            LineKind::Code { .. } => unreachable!("code handled by early return"),
            // `LineKind` is `#[non_exhaustive]`: any role added after this
            // build lowers as a paragraph rather than failing.
            _ => {
                let g0 = self.out.len();
                (g0, self.emit_inline(lo, hi))
            }
        };
        let g1 = self.out.len();
        self.segments.push(SegmentMap {
            content: lo..hi,
            generated: g0..g1,
            runs,
        });
        self.end_newline = false;
    }

    /// `#raw(block: true[, lang: "…"], "…")`: every line's text rides in the one
    /// string literal joined by an escaped `\n`, and is one `StringLit` run.
    fn emit_code(&mut self, range: Range<usize>, lang: Option<&str>, lo: usize, hi: usize) {
        let g0 = self.out.len();
        self.out.push_str("#raw(block: true");
        if let Some(l) = lang {
            self.out.push_str(", lang: \"");
            self.out.push_str(&escape_string(l));
            self.out.push('"');
        }
        self.out.push_str(", \"");
        let mut runs = Vec::new();
        for (idx, li) in range.clone().enumerate() {
            if idx > 0 {
                // Structural: outside any run.
                self.out.push_str(&escape_string("\n"));
            }
            let (l0, l1) = self.line_usv[li];
            let content: String = self.chars[l0..l1].iter().collect();
            let rg0 = self.out.len();
            self.out.push_str(&escape_string(&content));
            let rg1 = self.out.len();
            runs.push((l0..l1, rg0..rg1, EscapeCtx::StringLit));
        }
        self.out.push_str("\")");
        let g1 = self.out.len();
        self.segments.push(SegmentMap {
            content: lo..hi,
            generated: g0..g1,
            runs,
        });
    }

    /// Does the segment about to open sit at a line anchor: column 0 of a
    /// generated source line, indentation ahead of it not counting, or the head of a
    /// list item's body, which the parser reads as a line start of its own. A
    /// heading's body is not one, and neither is any position prose has reached.
    fn at_line_anchor(&self) -> bool {
        let head = |s: &str| {
            let s = s.trim_end_matches([' ', '\t']);
            s.is_empty() || s.ends_with('\n')
        };
        head(&self.out)
            || ["- ", "+ "]
                .iter()
                .any(|m| self.out.strip_suffix(m).is_some_and(head))
            || self.out.strip_suffix(". ").is_some_and(|s| {
                let before = s.trim_end_matches(|c: char| c.is_ascii_digit());
                before.len() < s.len() && head(before)
            })
    }

    /// Wrapping marks nest via a close-and-reopen boundary sweep; `code` marks
    /// render atomically as `#raw("…")`; interior `\n`s become `#linebreak()`.
    fn emit_inline(
        &mut self,
        lo: usize,
        hi: usize,
    ) -> Vec<(Range<usize>, Range<usize>, EscapeCtx)> {
        let mut runs = Vec::new();

        let (mut wraps, codes) = wraps_and_codes(self.overlapping_marks(lo, hi), lo, hi);
        // Atomic code spans can't carry partial styling.
        clip_wraps_to_codes(&mut wraps, &codes);

        // The scratch buffer's bytes land at `base` once appended, so each run's
        // generated span is `base + buf.len()`, absolute into `self.out`.
        let base = self.out.len();
        let open = if self.at_line_anchor() {
            Tail::Anchor
        } else {
            Tail::Text
        };
        let mut buf = String::new();
        sweep_marks(lo, hi, &wraps, &mut buf, open, |buf, pos, tail| {
            let c = self.chars[pos];
            if c == '\n' {
                buf.push_str("#linebreak()");
                return (pos + 1, Tail::Expr);
            }
            if c == ISLAND_SLOT {
                let markup = self.island_markup(pos);
                buf.push_str(&markup);
                // An island type this build does not know, and an empty table,
                // render nothing, closing the gap the slot held open.
                let left = match (markup.is_empty(), tail) {
                    (false, _) => Tail::Expr,
                    (true, Tail::Text) => Tail::Seam,
                    (true, t) => t,
                };
                return (pos + 1, left);
            }
            let (re, left, (content, g, ctx)) =
                emit_run(buf, pos, hi, &self.chars, &wraps, &codes, tail);
            runs.push((content, (base + g.start)..(base + g.end), ctx));
            (re, left)
        });
        self.out.push_str(&buf);
        runs
    }

    fn island_markup(&self, pos: usize) -> String {
        let idx = self.slot_offsets.partition_point(|&p| p < pos);
        let Some(isl) = self.rt.islands.get(idx) else {
            return String::new();
        };
        match KnownIslandType::parse(&isl.island_type) {
            // Declined, not unknown: what a content image's url names is
            // undecided, so this backend draws none and
            // `Emission::declined_images` counts them for the warning saying so.
            Some(KnownIslandType::Image) => String::new(),
            Some(KnownIslandType::Table) => table_markup(&isl.props),
            // Parallel to the HTML rule; a new known type is a compile error
            // here, not silence.
            None => String::new(),
        }
    }
}

/// A wrapping mark clipped to a segment; its close is always `]`.
struct Wrap {
    start: usize,
    end: usize,
    open: String,
}

fn wrap_open(kind: &MarkKind) -> String {
    match kind {
        MarkKind::Strong => "#strong[".to_string(),
        MarkKind::Emph => "#emph[".to_string(),
        MarkKind::Underline => "#underline[".to_string(),
        MarkKind::Strike => "#strike[".to_string(),
        _ => String::new(),
    }
}

/// Clip wrapping marks out of atomic `#raw(...)` interiors and drop any a span
/// swallowed whole, via the shared
/// [`clip_range_to_atomic`](quillmark_content::export::clip_range_to_atomic).
fn clip_wraps_to_codes(wraps: &mut Vec<Wrap>, codes: &[(usize, usize)]) {
    for w in wraps.iter_mut() {
        quillmark_content::export::clip_range_to_atomic(&mut w.start, &mut w.end, codes);
    }
    wraps.retain(|w| w.start < w.end);
}

/// The mark boundary sweep, shared by prose inline emission and table-cell
/// rendering: opens `wraps` (longer span first, coincident wraps in `wraps`
/// order) and closes-and-reopens deeper survivors at overlaps.
/// `emit_run(out, pos, tail)` writes the content at `pos` and returns the next
/// position and the [`Tail`] it leaves. Every wrap `open` ends `[`, and a
/// content block's head is a line start of Typst's own, so the anchor rearms at
/// each one; each `]` completes a call instead. `wraps` must already be clipped
/// against the code spans ([`clip_wraps_to_codes`]), so no wrap `end` hides
/// inside a span the callback's cursor jumps over.
fn sweep_marks(
    lo: usize,
    hi: usize,
    wraps: &[Wrap],
    out: &mut String,
    mut tail: Tail,
    mut emit_run: impl FnMut(&mut String, usize, Tail) -> (usize, Tail),
) {
    // Open marks, outermost first. Storing the index (not the boundary) keeps
    // each mark's identity, so a reopened mark re-emits its OWN delimiter: two
    // same-`end` links must not collapse, whatever their urls.
    let mut stack: Vec<usize> = Vec::new();
    let mut pos = lo;
    while pos <= hi {
        // Free overlap → proper nesting.
        if let Some(idx) = stack.iter().position(|&wi| wraps[wi].end == pos) {
            let mut reopen: Vec<usize> = Vec::new();
            while stack.len() > idx {
                let wi = stack.pop().unwrap();
                out.push(']');
                tail = Tail::Expr;
                if wraps[wi].end != pos {
                    reopen.push(wi);
                }
            }
            for wi in reopen.into_iter().rev() {
                out.push_str(&wraps[wi].open);
                tail = Tail::Anchor;
                stack.push(wi);
            }
        }
        if pos == hi {
            break;
        }
        let mut opening: Vec<usize> = (0..wraps.len()).filter(|&wi| wraps[wi].start == pos).collect();
        // No tie-break beyond `wraps` order, which the stable sort keeps.
        // `wraps` follows the marks, canonically sorted by `(start, end,
        // MarkKind::sort_key)` over their **stored** spans — the order two
        // coincident marks nest in, and the only order the document defines.
        // Clipping ([`clip_wraps_to_codes`], and the window clamp above) can
        // make two marks coincide that did not, and those nest in their stored
        // order too rather than in a second one re-derived from the clip.
        opening.sort_by(|&a, &b| wraps[b].end.cmp(&wraps[a].end));
        for wi in opening {
            out.push_str(&wraps[wi].open);
            tail = Tail::Anchor;
            stack.push(wi);
        }
        let (next, left) = emit_run(out, pos, tail);
        tail = left;
        pos = next;
    }
    // The codegen embeds this markup in a `#let _qm = [ .. ]` block that one
    // unclosed `[` would break, failing the whole helper file's parse. Clipping
    // keeps every wrap `end` reachable, so this normally drains nothing.
    while stack.pop().is_some() {
        out.push(']');
    }
}

/// The next position after `pos` at which a plain run must stop: any mark
/// start/end, any code start, an interior `\n`, an island slot, or `hi`.
fn next_boundary(
    pos: usize,
    hi: usize,
    chars: &[char],
    wraps: &[Wrap],
    codes: &[(usize, usize)],
) -> usize {
    let mut p = pos + 1;
    while p < hi {
        let c = chars[p];
        if c == '\n' || c == ISLAND_SLOT {
            break;
        }
        if wraps.iter().any(|w| w.start == p || w.end == p) {
            break;
        }
        if codes.iter().any(|(s, _)| *s == p) {
            break;
        }
        p += 1;
    }
    p
}

/// The wrapping/atomic marks overlapping `[lo, hi)`, clamped to it: a mark
/// entirely outside is dropped, one straddling is clipped to the window edges.
fn wraps_and_codes(marks: &[Mark], lo: usize, hi: usize) -> (Vec<Wrap>, Vec<(usize, usize)>) {
    let mut wraps = Vec::new();
    let mut codes = Vec::new();
    for m in marks {
        if m.end <= lo || m.start >= hi {
            continue;
        }
        let s = m.start.max(lo);
        let e = m.end.min(hi);
        if s >= e {
            continue;
        }
        match &m.kind {
            MarkKind::Code => codes.push((s, e)),
            MarkKind::Strong | MarkKind::Emph | MarkKind::Underline | MarkKind::Strike => {
                wraps.push(Wrap {
                    start: s,
                    end: e,
                    open: wrap_open(&m.kind),
                });
            }
            MarkKind::Link { url } => wraps.push(Wrap {
                start: s,
                end: e,
                open: format!("#link(\"{}\")[", escape_string(url)),
            }),
            // `Anchor` is identity, `Unknown` has no Typst spelling, and
            // `MarkKind` is `#[non_exhaustive]`: none contributes a wrap.
            _ => {}
        }
    }
    codes.sort_unstable();
    (wraps, codes)
}

/// One run of a mark sweep: the atomic `#raw(..)` code span starting at `pos`,
/// or the plain text up to the next boundary. Returns the position after it, the
/// [`Tail`] it leaves, and its `(content, generated, context)` pair, `generated`
/// indexing `out` itself. `tail` arms one of the two `\` guards — the
/// line-anchor one and [`continues_expr`]'s — whose byte sits *outside* the
/// run's window so `generated == escape_markup(content)` stays exact.
///
/// Under [`Tail::Anchor`] a run opening with trivia — spaces, tabs, and the
/// [`reads_as_newline`] characters [`escape_markup`] lowers to a space — stops
/// at the first character that is none of them: Typst reads trivia as holding
/// the anchor open behind it, while `\` before a space is its linebreak rather
/// than an escape, so the guard byte has to land on the marker itself.
fn emit_run(
    out: &mut String,
    pos: usize,
    hi: usize,
    chars: &[char],
    wraps: &[Wrap],
    codes: &[(usize, usize)],
    tail: Tail,
) -> (usize, Tail, (Range<usize>, Range<usize>, EscapeCtx)) {
    if let Some(&(cs, ce)) = codes.iter().find(|(s, _)| *s == pos) {
        let content: String = chars[cs..ce].iter().collect();
        out.push_str("#raw(\"");
        let g0 = out.len();
        out.push_str(&escape_string(&content));
        let g1 = out.len();
        out.push_str("\")");
        return (ce, Tail::Expr, (cs..ce, g0..g1, EscapeCtx::StringLit));
    }
    let mut re = next_boundary(pos, hi, chars, wraps, codes);
    let trivia = |c: char| c == ' ' || c == '\t' || reads_as_newline(c);
    if tail == Tail::Anchor && trivia(chars[pos]) {
        re = (pos..re).find(|&p| !trivia(chars[p])).unwrap_or(re);
    }
    let content: String = chars[pos..re].iter().collect();
    let guarded = match tail {
        Tail::Anchor => opens_line_anchor(&content),
        Tail::Expr => continues_expr(&content),
        Tail::Seam => couples_across(out.chars().last(), &content),
        Tail::Text => false,
    };
    if guarded {
        out.push('\\');
    }
    let g0 = out.len();
    out.push_str(&escape_markup(&content));
    let g1 = out.len();
    let left = match tail {
        Tail::Anchor if content.chars().all(trivia) => Tail::Anchor,
        _ => Tail::Text,
    };
    (re, left, (pos..re, g0..g1, EscapeCtx::Markup))
}

/// A cell is flat inline (no islands, no line breaks), so its markup carries no
/// source-map runs. It opens at the head of the `[…]` [`table_markup`] wraps it
/// in, which is a line anchor.
fn cell_markup(text: &str, marks: &[Mark]) -> String {
    let chars: Vec<char> = text.chars().collect();
    let (mut wraps, codes) = wraps_and_codes(marks, 0, chars.len());
    clip_wraps_to_codes(&mut wraps, &codes);
    let mut out = String::new();
    sweep_marks(0, chars.len(), &wraps, &mut out, Tail::Anchor, |out, pos, tail| {
        let (re, left, _) = emit_run(out, pos, chars.len(), &chars, &wraps, &codes, tail);
        (re, left)
    });
    out
}

/// Each cell is canonical `{text, marks}` rendered through [`cell_markup`], so a
/// formatted cell reaches byte parity with the oracle, no markdown re-parse.
fn table_markup(props: &serde_json::Value) -> String {
    let header = props.get("header").and_then(|v| v.as_array());
    let rows = props.get("rows").and_then(|v| v.as_array());
    let aligns = props.get("aligns").and_then(|v| v.as_array());
    // The widest row, not just the header: an editor-built island can carry a
    // short header over wider data rows, and `columns: 0` fails to compile.
    let mut cols = header.map(|h| h.len()).unwrap_or(0);
    if let Some(rs) = rows {
        for row in rs {
            if let Some(r) = row.as_array() {
                cols = cols.max(r.len());
            }
        }
    }
    // `Content::validate` accepts an empty table island, so this is reachable;
    // emit nothing, matching `export::emit_table`.
    if cols == 0 {
        return String::new();
    }

    let cell = |v: &serde_json::Value| {
        let (text, marks) = quillmark_content::serial::parse_cell(v);
        cell_markup(&text, &marks)
    };

    let mut out = String::from("#table(\n");
    out.push_str(&format!("  columns: {},\n", cols));
    if let Some(al) = aligns {
        if al
            .iter()
            .any(|a| a.as_str().map(|s| s != "none").unwrap_or(false))
        {
            out.push_str("  align: (");
            for (i, a) in al.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                out.push_str(match a.as_str().unwrap_or("none") {
                    "left" => "left",
                    "center" => "center",
                    "right" => "right",
                    _ => "auto",
                });
            }
            out.push_str("),\n");
        }
    }
    out.push_str("  table.header(");
    if let Some(h) = header {
        for c in h {
            out.push('[');
            out.push_str(&cell(c));
            out.push_str("], ");
        }
    }
    out.push_str("),\n");
    if let Some(rs) = rows {
        for row in rs {
            if let Some(r) = row.as_array() {
                out.push_str("  ");
                for c in r {
                    out.push('[');
                    out.push_str(&cell(c));
                    out.push_str("], ");
                }
                out.push('\n');
            }
        }
    }
    out.push(')');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use quillmark_content::import::from_markdown;
    use typst::syntax::SyntaxKind;

    fn emit(md: &str) -> Emission {
        let rt = from_markdown(md).expect("import");
        assert_eq!(rt.validate(), Ok(()), "content invariants for {md:?}");
        emit_content(&rt).expect("emit")
    }

    #[test]
    fn a_leaf_before_a_container_run_is_its_own_block() {
        let out = emit("a\n\n> b").markup;
        assert!(out.contains('a'), "leaf lost: {out:?}");
        assert!(
            out.find('a').unwrap() < out.find("quote").unwrap(),
            "leaf swallowed into the quote: {out:?}"
        );
    }

    /// The sample set [`runs_map_content_to_generated_bytes`] scans.
    fn sample_inputs() -> Vec<&'static str> {
        vec![
            // headings
            "# Heading 1",
            "## Heading 2",
            "### Heading 3",
            "#### Heading 4",
            "##### Heading 5",
            "###### Heading 6",
            "## Heading with **bold** and _italic_",
            "# Heading with $math$ and #functions",
            "# First\n\n## Second\n\n### Third",
            "# Heading\n\nThis is a paragraph.",
            "## Code example: `fn main()`",
            "#",
            // paragraphs / breaks
            "This is a paragraph.",
            "First paragraph.\n\nSecond paragraph.",
            "Line one  \nLine two",
            "Line one\\\nLine two",
            "a  \nb  \nc",
            "Line one\nLine two",
            "This is some\ntext on multiple\nlines",
            "P1.\n\nP2.\n\nP3.\n\nP4.\n\nP5.",
            // inline formatting
            "This is **bold**, _italic_, and ~~strikethrough~~ text.",
            "**bold**",
            "__bolded__",
            "*italic*",
            "~~strike~~",
            "**bold _and italic_**",
            "**_strong then emph_**",
            "**bold**text",
            "a*sdfasd*f",
            "word**bold**more",
            "*Write y*our paragraphs here.",
            "**a** __b__ **c**",
            "This is <u>underlined</u> text.",
            "pre<u>mid</u>post",
            "<U>upper</U>",
            "before <span class=\"x\">inner</span> after",
            "line1<br>line2",
            // inline code
            "`code`",
            "Text with `inline code` here",
            "`*#$<>`",
            "`` `code` ``",
            // links
            "[Link text](https://example.com)",
            "Visit [our site](https://example.com) for more.",
            "[Link](https://example.com/foo_bar)",
            "[Link](#anchor)",
            "[*bold* link](https://example.com)",
            "[Click 🎉](https://example.com)",
            "Check out https://example.com for more.",
            "// This should not be a comment",
            "Some text // with slashes in the middle",
            // escaping
            "pages 3--5, an em---dash, wait... and -5 degrees",
            "a soft-?hyphen, well-known, 3-5, a. b",
            "he said \"hi\" and 'bye'",
            "**bold**-5 and **t.**..",
            "Typst uses * for bold and # for functions.",
            "Use [brackets] and $math$ symbols.",
            "Text {{ content }}",
            "Hello~World",
            "Use path/to/file for the file",
            "Path: C:\\\\Users\\\\file",
            // guarded runs, whose `\` sits outside the window
            "`x`(y)",
            "**b**(y)",
            "  = x",
            // thematic breaks
            "one\n\n---\n\ntwo",
            "one\n\n***\n\ntwo",
            "one\n\n___\n\ntwo",
            // lists
            "- Item 1\n- Item 2\n- Item 3",
            "1. First\n2. Second\n3. Third",
            "3. Three\n4. Four\n5. Five",
            "0. Zero\n1. One",
            "1. a\n2. b\n\ntext\n\n5. c\n6. d",
            "- Item 1\n- Item 2\n  - Nested item\n- Item 3",
            "- Level 1\n  - Level 2\n    - Level 3",
            "- Bullet item\n\n1. Ordered item\n2. Another ordered",
            "- **Bold** item\n- _Italic_ item\n- `Code` item",
            "- First line.\n\n  Second line.",
            "- Para 1.\n\n  Para 2.\n\n  Para 3.",
            "- Item 1\n\n  More text.\n\n- Item 2",
            "1. First para.\n\n   Second para.\n\n2. Next item.",
            "1. First\n   - Nested bullet\n   - Another bullet\n2. Second",
            "- Item text\n\n  ```\n  code here\n  ```",
            "- First para.\n\n  ```\n  code\n  ```\n\n  After code.",
            // code fences
            "```rust\nfn main() {}\n```",
            "```\nhello\n```",
            "````\n```\nnested\n```\n````",
            "```\n*bold* #heading $math$\n```",
            "    fn main() {}\n    println!()",
            "```rust#evil\ncode\n```",
            "```c++\ncode\n```",
            // images
            "![alt text](path/to/img.png)",
            "![](x.png)",
            "![a *b* `c`](x.png)",
            // tables (plain cells only: formatted cells are a residual)
            "| Name | Age |\n|------|-----|\n| Alice | 30 |\n| Bob | 25 |",
            "| A | B |\n|---|---|\n| 1 | 2 |",
            "| L | C | R |\n|:---|:---:|---:|\n| a | b | c |",
            "| L | D | R |\n|:---|---|---:|\n| a | b | c |",
            "| Name | Value |\n|------|-------|\n",
            "| A | B | C |\n|---|---|---|\n| | | |",
            "| A | B | C |\n|---|---|---|\n| 1 | 2 |",
            "| A | B |\n|---|---|\n| 1 | 2 | 3 |",
            "| H |\n|:--|\n| x |",
            "| L | C | R | D |\n|:---|:---:|---:|---|\n| a | b | c | d |",
            "| A | B | C | D | E | F |\n|---|---|---|---|---|---|\n| 1 | 2 | 3 | 4 | 5 | 6 |",
            "- item1\n- item2\n\n| A |\n|---|\n| 1 |",
            "| Status |\n|--------|\n| ✅ Done |",
            "Before.\n\n| A |\n|---|\n| 1 |\n\nAfter.",
            "# Title\n\n| A |\n|---|\n| 1 |",
            // formatted cells (carried as {text, marks}, no re-parse)
            "| Name | Note |\n|------|------|\n| **bold** | _italic_ |",
            "| Func | Desc |\n|------|------|\n| `foo()` | does stuff |",
            "| Site |\n|------|\n| [Example](https://example.com) |",
            "| A |\n|---|\n| ~~deleted~~ |",
            "| A |\n|---|\n| **bold** and _italic_ |",
            "| A |\n|---|\n| <u>underlined</u> |",
            "| A |\n|---|\n| use #tag |",
            "| A |\n|---|\n| a\\|b |",
            "| A |\n|---|\n| $100 @ref ~space {brace} |",
            "| A |\n|---|\n| a // comment |",
            "| A |\n|---|\n| line1<br>line2 |",
            "| Bold | Link |\n|------|------|\n| **b** | [x](https://e.com) |",
            "| Mixed |\n|-------|\n| a **b** `c` [d](https://e.com) ~~e~~ |",
            // mixed
            "A paragraph with **bold** and a [link](https://example.com).\n\nAnother paragraph with `inline code`.\n\n- A list item\n- Another item",
            "# Title\n\nThis is a paragraph with **bold** and *italic* text.\n\n## Section\n\n- List item 1\n- List item 2 with [link](https://example.com)\n\nMore text with `inline code`.",
            // unicode
            "你好世界",
            "**你好** _世界_",
            "Hello 🎉 World 🚀",
            "مرحبا بالعالم",
        ]
    }

    #[test]
    fn empty_and_blank_emit_nothing() {
        for md in ["", "   ", "\n\n\n", "   \n   \n   "] {
            assert_eq!(emit(md).markup, "", "for {md:?}");
        }
    }

    // ---- inline lowering (richtext(inline)) ----

    #[test]
    fn inline_emits_no_block_terminator() {
        let rt = from_markdown("A **bold** subject").expect("import");
        assert!(rt.is_inline());
        let inline = emit_content_inline(&rt).expect("emit").markup;
        assert_eq!(inline, "A #strong[bold] subject");
        assert!(!inline.contains("\n\n"), "no parbreak in {inline:?}");
        let block = emit_content(&rt).expect("emit").markup;
        assert!(block.ends_with("\n\n"), "block path keeps its terminator");
    }

    #[test]
    fn inline_falls_back_to_block_for_non_inline_content() {
        for md in ["# Heading", "one\n\ntwo", "- item"] {
            let rt = from_markdown(md).expect("import");
            assert!(!rt.is_inline(), "{md:?} is not inline");
            assert_eq!(
                emit_content_inline(&rt).expect("emit").markup,
                emit_content(&rt).expect("emit").markup,
                "non-inline {md:?} must fall back to block lowering"
            );
        }
    }

    /// The blocks Typst's own parser reads as `kind` at the markup's top level,
    /// as source text. What a list contains is the parser's call: a container
    /// written to column 0 ends the list, and the item it belonged to comes
    /// back without it.
    fn top_level(markup: &str, kind: SyntaxKind) -> Vec<String> {
        typst::syntax::parse(markup)
            .children()
            .filter(|n| n.kind() == kind)
            .map(|n| n.full_text().to_string())
            .collect()
    }

    #[test]
    fn a_quote_in_an_item_stays_in_the_item() {
        let out = emit("- Alpha\n\n  > quoted\n\n  Beta\n\n- Gamma").markup;
        let items = top_level(&out, SyntaxKind::ListItem);
        assert_eq!(items.len(), 2, "the list broke apart: {out:?}");
        assert!(
            items[0].contains("quoted") && items[0].contains("Beta"),
            "the quote or the block after it left the item: {out:?}"
        );
    }

    #[test]
    fn a_quote_in_an_ordered_item_does_not_restart_the_numbering() {
        let out = emit("1. Alpha\n\n   > quoted\n\n   Beta\n\n2. Gamma").markup;
        let items = top_level(&out, SyntaxKind::EnumItem);
        assert_eq!(items.len(), 2, "the list broke apart: {out:?}");
        assert!(
            items[0].contains("quoted") && items[0].contains("Beta"),
            "the quote or the block after it left the item: {out:?}"
        );
        assert!(
            !items[1].starts_with("1."),
            "the second item restated the start: {out:?}"
        );
    }

    /// A container this build does not know lowers transparently: no wrapper
    /// markup, and no move out of the item either.
    #[test]
    fn an_unknown_container_in_an_item_stays_in_the_item() {
        use quillmark_content::model::Line;
        let item = || Container::ListItem {
            ordered: false,
            start: 1,
            ordinal: 0,
            instance: 0,
        };
        let roster = Container::Unknown {
            tag: "roster".to_string(),
            attrs: serde_json::Value::Null,
            instance: 0,
        };
        let rt = Content::new(
            "Alpha\nRoster\nBeta".to_string(),
            vec![
                Line::new(LineKind::Para).with_containers(vec![item()]),
                Line::new(LineKind::Para).with_containers(vec![item(), roster]),
                Line::new(LineKind::Para).with_containers(vec![item()]),
            ],
        )
        .into_normalized();
        assert_eq!(rt.validate(), Ok(()));
        let out = emit_content(&rt).unwrap().markup;
        let items = top_level(&out, SyntaxKind::ListItem);
        assert_eq!(items.len(), 1, "the item broke apart: {out:?}");
        assert!(
            items[0].contains("Roster") && items[0].contains("Beta"),
            "the container or the block after it left the item: {out:?}"
        );
    }

    // ---- intentional divergence: block quotes render ----

    #[test]
    fn block_quote_renders_not_flattened() {
        let out = emit("> quoted text").markup;
        assert!(
            out.contains("#quote(block: true)["),
            "quote must render, got {out:?}"
        );
        assert!(out.contains("quoted text"), "quote body present: {out:?}");
    }

    #[test]
    fn thematic_break_renders_line() {
        for src in ["---", "***", "___"] {
            let out = emit(&format!("one\n\n{src}\n\ntwo")).markup;
            assert_eq!(
                out, "one\n\n#line(length: 100%)\n\ntwo\n\n",
                "source: {src}, got {out:?}"
            );
        }
    }

    #[test]
    fn formatted_table_cell_renders_marks() {
        let md = "| Name | Note |\n|------|------|\n| **bold** | _italic_ |";
        let got = emit(md).markup;
        assert!(got.contains("#strong[bold]"), "got {got:?}");
        assert!(got.contains("#emph[italic]"), "got {got:?}");
    }

    /// Coincident `strong`+`emph` lose their source nesting order at import, so
    /// the emitter nests them in the order the canonical form stores.
    #[test]
    fn coincident_strong_emph_nests_canonically() {
        for m in ["**_x_**", "***x***", "_**x**_"] {
            assert_eq!(emit(m).markup, "#emph[#strong[x]]\n\n");
        }
    }

    /// A code span clips two links down to one range, so they coincide in
    /// `wraps` without coinciding in the document. They nest in their stored
    /// order — `z` starts first — not in an order re-derived from the clip,
    /// which would put `a` outside and hand the text to the wrong target.
    #[test]
    fn clipping_two_marks_together_nests_them_in_their_stored_order() {
        use quillmark_content::model::Line;
        let rt = Content::new("abcdefghij".to_string(), vec![Line::new(LineKind::Para)])
            .with_marks(vec![
                Mark::new(0, 3, MarkKind::Code),
                Mark::new(1, 10, MarkKind::Link { url: "z".into() }),
                Mark::new(3, 10, MarkKind::Link { url: "a".into() }),
            ])
            .into_normalized();
        assert_eq!(rt.validate(), Ok(()));
        assert_eq!(
            emit_content(&rt).unwrap().markup,
            "#raw(\"abc\")#link(\"z\")[#link(\"a\")[defghij]]\n\n"
        );
    }

    /// The cluster opening at `chars[i]`: the content chars it spans and the
    /// bytes it generates. A second statement of the escape rules, which is why
    /// it calls [`escape_markup`] one char at a time — where no lookahead rule
    /// fires. Lookahead is markup only; `escape_string` leaves `//`, `--` and
    /// `...` alone.
    fn cluster_at(chars: &[char], i: usize, ctx: EscapeCtx) -> (usize, String) {
        let at = |k: usize| chars.get(i + k).copied();
        if ctx == EscapeCtx::Markup {
            if chars[i] == '/' && at(1) == Some('/') {
                return (2, r"\/\/".to_string());
            }
            let couples = match chars[i] {
                '-' => matches!(at(1), Some('-' | '?')) || at(1).is_some_and(char::is_numeric),
                '.' => at(1) == Some('.') && at(2) == Some('.'),
                _ => false,
            };
            if couples {
                return (1, format!("\\{}", chars[i]));
            }
        }
        let s = chars[i].to_string();
        let bytes = match ctx {
            EscapeCtx::Markup => escape_markup(&s),
            EscapeCtx::StringLit => escape_string(&s),
        };
        (1, bytes)
    }

    /// Reconstructs a run's generated bytes cluster by cluster, for
    /// byte-for-byte comparison against the real escapes.
    fn scan_reconstruct(run: &str, ctx: EscapeCtx) -> String {
        let chars: Vec<char> = run.chars().collect();
        let mut out = String::new();
        let mut i = 0;
        while i < chars.len() {
            let (n, bytes) = cluster_at(&chars, i, ctx);
            out.push_str(&bytes);
            i += n;
        }
        out
    }

    #[test]
    fn escape_tripwire_markup() {
        let samples = [
            "plain text",
            "https://example.com",
            "a // b // c",
            "///",
            "Use * for _bold_ and # for @refs",
            "{braces} [brackets] $math$ <tags>",
            "C:\\Users\\file",
            "tilde~and`backtick`",
            "你好 🎉 mixed",
            "file://path//to//x",
            "pages 3--5",
            "an em---dash",
            "wait...",
            "....",
            "soft-?hyphen",
            "-5 degrees",
            "a-b and a - b",
            "\"double\" and 'single'",
            "a\u{000B}b\u{000C}c\u{0085}d\u{2028}e\u{2029}f",
        ];
        for s in samples {
            assert_eq!(
                scan_reconstruct(s, EscapeCtx::Markup),
                escape_markup(s),
                "markup scan != escape_markup for {s:?}"
            );
        }
    }

    /// What Typst resolves a markup fragment to: its characters, and the leaf
    /// kinds it read them as. A comment resolves to nothing and a shorthand to
    /// the codepoint it substitutes, so either shows as a mismatch rather than
    /// as its own source text.
    fn resolve(markup: &str) -> (String, Vec<SyntaxKind>) {
        use typst::syntax::{ast, ast::AstNode, SyntaxNode};

        fn walk(n: &SyntaxNode, text: &mut String, kinds: &mut Vec<SyntaxKind>) {
            if n.children().len() > 0 {
                for c in n.children() {
                    walk(c, text, kinds);
                }
                return;
            }
            kinds.push(n.kind());
            match n.kind() {
                SyntaxKind::Escape => text.push(ast::Escape::from_untyped(n).unwrap().get()),
                SyntaxKind::Shorthand => {
                    text.push(ast::Shorthand::from_untyped(n).unwrap().get())
                }
                SyntaxKind::LineComment | SyntaxKind::BlockComment => {}
                _ => text.push_str(n.leaf_text()),
            }
        }

        let (mut text, mut kinds) = (String::new(), Vec::new());
        walk(&typst::syntax::parse(markup), &mut text, &mut kinds);
        (text, kinds)
    }

    /// What escaped document text may lower to. `SmartQuote` is allowed by
    /// policy: `'` and `"` stay authored so a quill picks its own typography.
    const ALLOWED_LEAVES: &[SyntaxKind] = &[
        SyntaxKind::Text,
        SyntaxKind::Space,
        SyntaxKind::Parbreak,
        SyntaxKind::Escape,
        SyntaxKind::SmartQuote,
    ];

    /// Escaped text reaches the page as the characters the document holds, read
    /// back through Typst's own parser. The `x` prefix puts the fragment past
    /// `at_start`, whose markers are [`emit_run`]'s guard rather than
    /// [`escape_markup`]'s.
    #[test]
    fn escaped_markup_resolves_to_the_authored_text() {
        let samples = [
            "pages 3--5",
            "an em---dash, and ----",
            "wait... really....",
            "a soft-?hyphen",
            "-5 degrees, -٣ too",
            "* _ ` # [ ] { } $ < > @ ~ \\",
            "a // b /* c */ d",
            "https://example.com and http://x",
            "and/or, path/to/file",
            "1. not a list, - not an item, = not a heading",
            "he said \"hi\" and 'bye'",
            "你好 🎉 مرحبا",
            "trailing backslash \\",
            "-", "--", "---", "...", "//", "-?", "-1",
        ];
        for s in samples {
            let (text, kinds) = resolve(&format!("x{}", escape_markup(s)));
            assert_eq!(text, format!("x{s}"), "escaping {s:?} did not survive Typst");
            for k in kinds {
                assert!(ALLOWED_LEAVES.contains(&k), "{s:?} lowered to a {k:?} leaf");
            }
        }
    }

    /// The emitter lowers exactly Typst's own newline set, less the `\n` it
    /// writes as a line boundary, so a Typst upgrade that widens the set fails
    /// here rather than in a rendered document.
    #[test]
    fn the_lowered_set_is_typsts_newlines_less_lf() {
        for c in ('\0'..=char::MAX).filter(|c| *c != '\n') {
            assert_eq!(reads_as_newline(c), typst::syntax::is_newline(c), "{c:?}");
        }
    }

    /// A character Typst reads as a newline lowers to a space, so the text
    /// behind it stays prose instead of opening a heading, list or term marker,
    /// and a pair of them does not split the paragraph. Such a character reaches
    /// the emitter only from a content the ingress never made — hand-built, or
    /// decoded from storage — so the content is built here rather than imported.
    #[test]
    fn a_stray_newline_lowers_to_a_space_and_opens_no_block() {
        use quillmark_content::model::Line;
        for c in ('\0'..=char::MAX).filter(|c| *c != '\n' && reads_as_newline(*c)) {
            let text = format!("{c}- item{c}{c}tail{c}= not a heading");
            let rt = Content::new(text, vec![Line::new(LineKind::Para)]).into_normalized();
            assert!(rt.validate().is_err(), "{c:?} passes the content invariants");

            let markup = emit_content(&rt).unwrap().markup;
            assert_eq!(markup, " \\- item  tail = not a heading\n\n", "for {c:?}");
            for k in resolve(&markup).1 {
                assert!(ALLOWED_LEAVES.contains(&k), "{c:?} lowered to a {k:?} leaf");
            }
        }
    }

    /// The escape lands on the shorthand's head and leaves the rest of the run
    /// plain — save a `-` before a number, which the rule takes wherever it
    /// reads one.
    #[test]
    fn shorthand_heads_are_escaped_and_nothing_else_is() {
        for (md, want) in [
            ("pages 3--5", "pages 3\\-\\-5\n\n"),
            ("an em---dash", "an em\\-\\--dash\n\n"),
            ("wait...", "wait\\...\n\n"),
            ("wait....", "wait\\.\\...\n\n"),
            ("a soft-?hyphen", "a soft\\-?hyphen\n\n"),
            ("-5 degrees", "\\-5 degrees\n\n"),
            ("well-known, a. b, 1.5", "well-known, a. b, 1.5\n\n"),
            ("a 3-5 range", "a 3\\-5 range\n\n"),
        ] {
            assert_eq!(emit(md).markup, want, "for {md:?}");
        }
        // The line-anchor guard and the `-` escape are complementary: the marker
        // fires on a space after it, the shorthand on `-`, `?` or a number.
        assert_eq!(emit_marked("- x", vec![]), "\\- x\n\n");
        assert_eq!(emit_marked("-5", vec![]), "\\-5\n\n");
    }

    /// A mark ends a text run, so Typst reads the text behind it as a fresh
    /// token where prose would have carried one on: `#strong[x]-5` is a minus
    /// sign the content never held.
    #[test]
    fn a_mark_boundary_does_not_fabricate_a_shorthand() {
        assert_eq!(
            emit_marked("x-5", vec![Mark::new(0, 1, MarkKind::Strong)]),
            "#strong[x]\\-5\n\n"
        );
    }

    fn substituting_leaves(markup: &str) -> Vec<SyntaxKind> {
        resolve(markup)
            .1
            .into_iter()
            .filter(|k| {
                matches!(
                    k,
                    SyntaxKind::Shorthand | SyntaxKind::LineComment | SyntaxKind::BlockComment
                )
            })
            .collect()
    }

    /// Escaping is per run, and what the emitter writes between two runs decides
    /// whether their text abuts. A coupling straddling such a join belongs to
    /// neither run's escape, so no emission may reach a shorthand or a comment —
    /// whatever the marks and islands.
    #[test]
    fn no_emission_forms_a_shorthand_or_a_comment() {
        use quillmark_content::model::{Island, Line};

        let mut cases: Vec<String> = sample_inputs().iter().map(|md| emit(md).markup).collect();

        let all = |t: &str, k| vec![Mark::new(0, t.chars().count(), k)];
        for (text, marks) in [
            ("x-5", all("x", MarkKind::Strong)),
            ("x-5", vec![Mark::new(0, 1, MarkKind::Strong)]),
            ("wait...", vec![Mark::new(0, 5, MarkKind::Strong)]),
            ("a//b", vec![Mark::new(0, 2, MarkKind::Emph)]),
            ("a--b", vec![Mark::new(0, 2, MarkKind::Code)]),
        ] {
            cases.push(emit_marked(text, marks));
        }

        // An island this build renders as nothing closes the gap its slot held.
        for ty in ["widget", "table", "image"] {
            for text in ["a/{}/b", "a-{}-b", "a-{}?b", "a-{}5b", "a.{}..b", "a..{}.b"] {
                let text = text.replace("{}", &ISLAND_SLOT.to_string());
                let rt = Content::new(text.clone(), vec![Line::new(LineKind::Para)])
                    .with_islands(vec![Island::new("isl-0".into(), ty.into())])
                    .into_normalized();
                assert_eq!(rt.validate(), Ok(()), "content invariants for {text:?}");
                let markup = emit_content(&rt).unwrap().markup;
                assert!(
                    !markup.contains(ISLAND_SLOT),
                    "the slot char reached the markup: {markup:?}"
                );
                // The guard breaks the coupling by escaping, so the text either
                // side of the closed gap still reaches the page as itself.
                let authored: String = text.chars().filter(|c| *c != ISLAND_SLOT).collect();
                assert_eq!(
                    resolve(markup.trim_end()).0,
                    authored,
                    "the seam guard moved the text for {text:?}"
                );
                cases.push(markup);
            }
        }

        for markup in cases {
            assert_eq!(
                substituting_leaves(&markup),
                Vec::<SyntaxKind>::new(),
                "substitution in {markup:?}"
            );
        }
    }

    #[test]
    fn escape_tripwire_string_lit() {
        let samples = [
            "plain text",
            "https://example.com",
            "a // b",
            "say \"hi\"\nnow\ttab",
            "C:\\Users\\file",
            "control\x07bell",
            "你好 🎉 mixed",
            "trailing//",
        ];
        for s in samples {
            assert_eq!(
                scan_reconstruct(s, EscapeCtx::StringLit),
                escape_string(s),
                "string scan != escape_string for {s:?}"
            );
        }
    }

    /// Per content char, the `(content_index, gen_byte_start)` of the cluster it
    /// opens: the ground truth the run inverters are checked against.
    fn cluster_starts(run: &str, ctx: EscapeCtx) -> (String, Vec<(usize, usize)>) {
        let chars: Vec<char> = run.chars().collect();
        let mut generated = String::new();
        let mut starts = Vec::new();
        let mut i = 0;
        while i < chars.len() {
            // A multi-char cluster opens at its first content char.
            starts.push((i, generated.len()));
            let (n, bytes) = cluster_at(&chars, i, ctx);
            generated.push_str(&bytes);
            i += n;
        }
        (generated, starts)
    }

    #[test]
    fn run_offset_inversion_is_cluster_exact() {
        let cases = [
            (EscapeCtx::Markup, "plain"),
            (EscapeCtx::Markup, "a*b_c#d"),
            (EscapeCtx::Markup, "http://a//b"),
            (EscapeCtx::Markup, "///x"),
            (EscapeCtx::Markup, "你好*x*🎉"),
            (EscapeCtx::Markup, "C:\\x"),
            (EscapeCtx::Markup, "3--5"),
            (EscapeCtx::Markup, "wait..."),
            (EscapeCtx::Markup, "-5 and -?x"),
            (EscapeCtx::Markup, "a\u{0085}b\u{2028}c"),
            (EscapeCtx::StringLit, "fn add(a, b)"),
            (EscapeCtx::StringLit, "a\"b\\c"),
            (EscapeCtx::StringLit, "tab\there"),
            (EscapeCtx::StringLit, "bell\x07end"),
            (EscapeCtx::StringLit, "a//b"),
        ];
        for (ctx, run) in cases {
            let (generated, starts) = cluster_starts(run, ctx);
            // Every byte inside cluster k inverts to that cluster's content char.
            for w in 0..starts.len() {
                let (content_i, byte_start) = starts[w];
                let byte_end = starts.get(w + 1).map(|s| s.1).unwrap_or(generated.len());
                for b in byte_start..byte_end {
                    assert_eq!(
                        invert_gen_offset(&generated, ctx, b),
                        content_i,
                        "byte {b} of {run:?} ({ctx:?}) floors to cluster {content_i}"
                    );
                }
                // The cluster's content start forward-maps to its byte start.
                assert_eq!(
                    forward_content_offset(&generated, ctx, content_i),
                    byte_start,
                    "content {content_i} of {run:?} ({ctx:?}) → byte {byte_start}"
                );
            }
            // Past-the-end saturates at the run's extents both ways.
            let content_len: usize = run.chars().count();
            assert_eq!(invert_gen_offset(&generated, ctx, generated.len()), content_len);
            assert_eq!(forward_content_offset(&generated, ctx, content_len), generated.len());
        }
    }

    #[test]
    fn runs_map_content_to_generated_bytes() {
        for md in sample_inputs() {
            let rt = from_markdown(md).unwrap();
            let ec = emit_content(&rt).unwrap();
            let chars: Vec<char> = rt.text.chars().collect();
            for seg in &ec.segments {
                // Segment window is within the markup and non-decreasing.
                assert!(seg.generated.start <= seg.generated.end && seg.generated.end <= ec.markup.len());
                for (content, generated, ctx) in &seg.runs {
                    let src: String = chars[content.clone()].iter().collect();
                    let expect = match ctx {
                        EscapeCtx::Markup => escape_markup(&src),
                        EscapeCtx::StringLit => escape_string(&src),
                    };
                    assert_eq!(
                        &ec.markup[generated.clone()],
                        expect,
                        "run bytes mismatch in {md:?}"
                    );
                    // Runs sit inside their segment's generated window.
                    assert!(generated.start >= seg.generated.start && generated.end <= seg.generated.end);
                }
            }
        }
    }

    /// Free-overlapping marks are never produced by import, only by an editor.
    #[test]
    fn overlapping_marks_close_and_reopen() {
        use quillmark_content::model::{Line, Mark};
        let rt = Content::new("abcdef".to_string(), vec![Line::new(LineKind::Para)])
            .with_marks(vec![
                Mark::new(0, 4, MarkKind::Strong),
                Mark::new(2, 6, MarkKind::Emph),
            ]);
        let rt = rt.into_normalized();
        assert_eq!(rt.validate(), Ok(()));
        let out = emit_content(&rt).unwrap().markup;
        assert_eq!(out, "#strong[ab#emph[cd]]#emph[ef]\n\n");
        // Bracket-balanced regardless.
        assert_eq!(out.matches('[').count(), out.matches(']').count());
    }

    /// A build that predates a construct renders it plainly instead of failing:
    /// an unknown line kind as a paragraph, an unknown container transparently.
    #[test]
    fn unknown_block_vocabulary_lowers_as_prose() {
        use quillmark_content::model::Line;
        let indent = || Container::Unknown {
            tag: "indent".to_string(),
            attrs: serde_json::Value::Null,
            instance: 0,
        };
        let rt = Content::new(
            "heads up\nsecond".to_string(),
            vec![
                Line::new(LineKind::Unknown {
                    tag: "callout".to_string(),
                    attrs: serde_json::json!({"variant": "warn"}),
                })
                .with_containers(vec![indent()]),
                Line::new(LineKind::Para)
                    .with_containers(vec![indent()])
                    .with_continues(true),
            ],
        );
        let rt = rt.into_normalized();
        assert_eq!(rt.validate(), Ok(()));
        // One block (the `continues` join is a hard break), no wrapper.
        assert_eq!(
            emit_content(&rt).unwrap().markup,
            "heads up#linebreak()second\n\n"
        );
        // Inside a known container the known wrapper still renders.
        let mut rt = rt.into_content();
        rt.lines[0].containers.insert(0, Container::Quote { instance: 0 });
        rt.lines[1].containers.insert(0, Container::Quote { instance: 0 });
        let rt = rt.into_normalized();
        assert_eq!(
            emit_content(&rt).unwrap().markup,
            "#quote(block: true)[\nheads up#linebreak()second\n\n]\n\n"
        );
    }

    /// Hand-placed `marks` reach the free-overlap shapes import never produces.
    fn emit_marked(text: &str, marks: Vec<Mark>) -> String {
        use quillmark_content::model::Line;
        let rt =
            Content::new(text.to_string(), vec![Line::new(LineKind::Para)]).with_marks(marks);
        let rt = rt.into_normalized();
        assert_eq!(rt.validate(), Ok(()), "content invariants");
        emit_content(&rt).unwrap().markup
    }

    fn balanced(out: &str) -> bool {
        out.matches('[').count() == out.matches(']').count()
    }

    #[test]
    fn every_wrap_mark_lowers_to_its_typst_function() {
        for (kind, expected) in [
            (MarkKind::Strong, "#strong[abc]\n\n"),
            (MarkKind::Emph, "#emph[abc]\n\n"),
            (MarkKind::Underline, "#underline[abc]\n\n"),
            (MarkKind::Strike, "#strike[abc]\n\n"),
        ] {
            let out = emit_marked(
                "abc",
                vec![Mark::new(0, 3, kind.clone())],
            );
            assert_eq!(out, expected, "{kind:?} lowers wrong");
        }
    }

    use quillmark_content::model::Mark;

    /// A wrap `end` inside an atomic code span must still close its bracket, or
    /// the generated helper file fails to parse.
    #[test]
    fn wrap_over_atomic_code_stays_balanced() {
        // Wrap starts first, ends inside the code: strong[0,4) + code[2,6).
        let out = emit_marked(
            "abcdef",
            vec![
                Mark::new(0, 4, MarkKind::Strong),
                Mark::new(2, 6, MarkKind::Code),
            ],
        );
        assert_eq!(out, "#strong[ab]#raw(\"cdef\")\n\n");
        assert!(balanced(&out));

        // Code starts first, wrap starts inside it: code[0,4) + strong[2,6).
        let out = emit_marked(
            "abcdef",
            vec![
                Mark::new(0, 4, MarkKind::Code),
                Mark::new(2, 6, MarkKind::Strong),
            ],
        );
        assert_eq!(out, "#raw(\"abcd\")#strong[ef]\n\n");
        assert!(balanced(&out));

        // A code span fully inside a wrap still nests (neither wrap edge is
        // interior to the code, so nothing is clipped): strong[0,6) + code[2,4).
        let out = emit_marked(
            "abcdef",
            vec![
                Mark::new(0, 6, MarkKind::Strong),
                Mark::new(2, 4, MarkKind::Code),
            ],
        );
        assert_eq!(out, "#strong[ab#raw(\"cd\")ef]\n\n");
        assert!(balanced(&out));
    }

    #[test]
    fn wrap_trailing_to_end_closes() {
        let out = emit_marked(
            "abcdef",
            vec![Mark::new(0, 6, MarkKind::Strong)],
        );
        assert_eq!(out, "#strong[abcdef]\n\n");
        assert!(balanced(&out));
    }

    /// Two overlapping `link` marks sharing an `end` but carrying distinct URLs
    /// must each reopen with their OWN URL.
    #[test]
    fn overlapping_links_reopen_with_correct_url() {
        let out = emit_marked(
            "abcdef",
            vec![
                Mark::new(0, 6, MarkKind::Link {
                        url: "wrong".into(),
                    }),
                Mark::new(0, 4, MarkKind::Strong),
                Mark::new(2, 6, MarkKind::Link {
                        url: "right".into(),
                    }),
            ],
        );
        // The reopened tail after the strong closes carries the inner link's URL.
        assert!(
            out.contains("#link(\"right\")[ef]"),
            "reopened link keeps its own URL, got {out:?}"
        );
        assert!(
            !out.contains("#link(\"wrong\")[ef]"),
            "reopen must not borrow the outer link's URL, got {out:?}"
        );
        assert!(balanced(&out));
    }

    /// `columns: 0` fails to compile.
    #[test]
    fn table_columns_span_widest_row() {
        let cell = |t: &str| serde_json::json!({ "text": t, "marks": [] });
        let props = serde_json::json!({
            "header": [ cell("H") ],
            "rows": [ [ cell("a"), cell("b"), cell("c") ] ],
        });
        let out = table_markup(&props);
        assert!(out.contains("columns: 3,"), "got {out:?}");

        // Empty header, populated rows: still counts the rows.
        let props = serde_json::json!({
            "header": [],
            "rows": [ [ cell("a"), cell("b") ] ],
        });
        let out = table_markup(&props);
        assert!(out.contains("columns: 2,"), "got {out:?}");
    }

    #[test]
    fn empty_table_emits_nothing() {
        let props = serde_json::json!({ "header": [], "aligns": [], "rows": [] });
        assert_eq!(table_markup(&props), "");
    }

    #[test]
    fn an_image_island_draws_nothing_and_is_counted() {
        let ec = emit("before ![alt](assets/logo.svg) after\n\n![x](y.png)");
        assert!(!ec.markup.contains("#image"), "got {:?}", ec.markup);
        assert!(!ec.markup.contains("assets/logo.svg"), "got {:?}", ec.markup);
        assert_eq!(ec.declined_images, 2);
        assert_eq!(emit("no images here").declined_images, 0);
    }

    #[test]
    fn segment_shape() {
        assert_eq!(
            emit("a  \nb  \nc").segments.len(),
            1,
            "hard-break paragraph"
        );
        assert_eq!(emit("```\nl1\nl2\nl3\n```").segments.len(), 1, "code fence");
        // A three-item list is three segments (one per item paragraph).
        assert_eq!(emit("- a\n- b\n- c").segments.len(), 3);
    }

    #[test]
    fn line_anchor_predicate() {
        for yes in [
            "= h", "== h", "- b", "+ n", "/ term: d", "1. i", "42. i",
            // Nothing after the marker: Typst reads the line's end as the space
            // it wants, so a run that is one bare marker opens a block too.
            "=", "==", "-", "+", "/", "1.", "42.",
        ] {
            assert!(opens_line_anchor(yes), "{yes:?} should trigger");
        }
        for no in [
            "=foo", "==foo", "-5 degrees", "and/or", "1.item", "1) i", "hi", "", " = x", "1",
        ] {
            assert!(!opens_line_anchor(no), "{no:?} should not trigger");
        }
    }

    /// The source map stays exact because the `\` sits outside every run's
    /// `generated` window.
    #[test]
    fn line_anchor_paragraph_prefixes_backslash() {
        // Bare paragraph starts → escaped.
        assert_eq!(emit_marked("= x", vec![]), "\\= x\n\n");
        assert_eq!(emit_marked("- x", vec![]), "\\- x\n\n");
        assert_eq!(emit_marked("+ x", vec![]), "\\+ x\n\n");
        assert_eq!(emit_marked("/ t: d", vec![]), "\\/ t: d\n\n");
        assert_eq!(emit_marked("1. x", vec![]), "\\1. x\n\n");
        // A paragraph that is one bare marker: the same escape, on the marker Typst
        // reads off the line's end. Unescaped, `/` alone is a term list missing its
        // colon and the compile fails outright.
        assert_eq!(emit_marked("/", vec![]), "\\/\n\n");
        assert_eq!(emit_marked("=", vec![]), "\\=\n\n");
        assert_eq!(emit_marked("-", vec![]), "\\-\n\n");
        // Non-trigger prose is untouched.
        assert_eq!(emit_marked("hello = x", vec![]), "hello = x\n\n");
        assert_eq!(emit_marked("=x no space", vec![]), "=x no space\n\n");
        // A wrap opens a content block, whose head is a line start of Typst's own.
        assert_eq!(
            emit_marked("= x", vec![Mark::new(0, 3, MarkKind::Strong)]),
            "#strong[\\= x]\n\n",
        );
        // Indentation is trivia and holds the anchor open behind it, so the guard
        // lands on the marker: before the space it would be Typst's linebreak.
        assert_eq!(emit_marked("  = x", vec![]), "  \\= x\n\n");
        assert_eq!(
            emit_marked("  = x", vec![Mark::new(0, 5, MarkKind::Emph)]),
            "#emph[  \\= x]\n\n",
        );

        // Source-map integrity: every run's generated slice equals the escape of
        // its content, and the leading `\` is not inside any run.
        use quillmark_content::model::Line;
        let rt = Content::new("= x".to_string(), vec![Line::new(LineKind::Para)]);
        let rt = rt.into_normalized();
        let ec = emit_content(&rt).unwrap();
        let chars: Vec<char> = rt.text.chars().collect();
        for seg in &ec.segments {
            for (content, generated, ctx) in &seg.runs {
                let src: String = chars[content.clone()].iter().collect();
                let expect = match ctx {
                    EscapeCtx::Markup => escape_markup(&src),
                    EscapeCtx::StringLit => escape_string(&src),
                };
                assert_eq!(&ec.markup[generated.clone()], expect, "run slices to its escape");
            }
        }
    }

    /// A `#…` expression the emitter wrote runs on into a `(`, a `.field` or a
    /// `;` directly after it, so those take the same `\` prefix as a line anchor.
    #[test]
    fn expression_tail_prefixes_backslash() {
        assert_eq!(emit("`x`(y)").markup, "#raw(\"x\")\\(y)\n\n");
        assert_eq!(emit("**b**(y)").markup, "#strong[b]\\(y)\n\n");
        assert_eq!(emit("`x`.len").markup, "#raw(\"x\")\\.len\n\n");
        assert_eq!(emit("`--force`; x").markup, "#raw(\"--force\")\\; x\n\n");
        assert_eq!(emit("**W**; x").markup, "#strong[W]\\; x\n\n");
        assert_eq!(emit("a\\\n; b").markup, "a#linebreak()\\; b\n\n");
        assert_eq!(emit("a\\\n(b)").markup, "a#linebreak()\\(b)\n\n");
        // Typst ends the expression on trivia, and on a `.` no identifier follows.
        assert_eq!(emit("`x` (y)").markup, "#raw(\"x\") (y)\n\n");
        assert_eq!(emit("`x`.5").markup, "#raw(\"x\").5\n\n");
        // Prose reaching a `(` is no expression tail.
        assert_eq!(emit("a(y)").markup, "a(y)\n\n");
    }

    /// Typst reads the guarded `;` as an `Escape`, not the `Semicolon` that
    /// ends an expression and renders nothing.
    #[test]
    fn guarded_semicolon_survives_the_parser() {
        use typst::syntax::{parse, SyntaxKind};

        let kinds = |src: &str| -> Vec<SyntaxKind> {
            parse(src).children().map(|c| c.kind()).collect()
        };
        assert!(kinds("#strong[b];c").contains(&SyntaxKind::Semicolon));
        assert!(!kinds(&emit("**b**;c").markup).contains(&SyntaxKind::Semicolon));
        assert!(kinds(&emit("**b**;c").markup).contains(&SyntaxKind::Escape));
    }

    /// Typst's own parser over the emitter's output: the block-level nodes it
    /// finds are exactly the ones the content asked for.
    #[test]
    fn typst_reads_only_the_blocks_the_content_asked_for() {
        use typst::syntax::{parse, SyntaxKind, SyntaxNode};

        fn blocks(n: &SyntaxNode, out: &mut Vec<SyntaxKind>) {
            if matches!(
                n.kind(),
                SyntaxKind::Heading
                    | SyntaxKind::ListItem
                    | SyntaxKind::EnumItem
                    | SyntaxKind::TermItem
            ) {
                out.push(n.kind());
            }
            for c in n.children() {
                blocks(c, out);
            }
        }
        let found = |markup: &str| {
            let mut v = Vec::new();
            blocks(&parse(markup), &mut v);
            v
        };

        let all = |text: &str, kind| vec![Mark::new(0, text.chars().count(), kind)];
        for (markup, want) in [
            // Column 0, with the marker ending the run or the line.
            (emit_marked("/ t", vec![]), vec![]),
            (emit_marked("/", vec![]), vec![]),
            (emit_marked("=", vec![]), vec![]),
            // Behind indentation, which Typst reads as trivia.
            (emit_marked("  / t", vec![]), vec![]),
            (emit_marked("\t- b", vec![]), vec![]),
            // A wrap's content block.
            (emit_marked("/ t", all("/ t", MarkKind::Strong)), vec![]),
            (emit_marked("= h", all("= h", MarkKind::Strong)), vec![]),
            (emit_marked("  - b", all("  - b", MarkKind::Emph)), vec![]),
            (emit_marked("1. n", all("1. n", MarkKind::Strike)), vec![]),
            // A table cell's.
            (
                emit("| / t | = h |\n| --- | --- |\n| - b | 1. n |").markup,
                vec![],
            ),
            // A list item's body head, whose own item is the one block here.
            (emit("- /").markup, vec![SyntaxKind::ListItem]),
            // Real blocks still reach Typst as blocks.
            (
                emit("# h\n\n- a\n- b").markup,
                vec![
                    SyntaxKind::Heading,
                    SyntaxKind::ListItem,
                    SyntaxKind::ListItem,
                ],
            ),
        ] {
            assert_eq!(found(&markup), want, "for {markup:?}");
        }
    }
}
