//! Generates the virtual `@local/quillmark-helper:0.1.0` package that provides
//! document data to Typst plates.
//!
//! `lib.typ` is regenerated per render as pure source text: no runtime data
//! processing. [`Codegen::emit_value`] walks the document data beside the
//! transform-schema node declaring it, so what a value lowers to is read off
//! that node at any depth. Content lowers to markup block bindings (`#let _qm_cN
//! = [ .. ]`) via [`emit_content`], every other type to its native Typst value;
//! the document data is a Typst literal (`#let data = ( .. )`) referencing those
//! blocks. The date closures behind `display` are keyed by schema address
//! instead, since a plate reaches for them by name rather than through a value.
//!
//! Output is **canonical**: dict keys emit in sorted order at every level (via
//! [`sorted`]), so equal data produces byte-equal source regardless of the
//! caller's field order. `$cards` array order is semantic and preserved.

use std::collections::HashMap;
use std::ops::Range;

use crate::emit::{
    emit_content, emit_content_inline, escape_string, EmitError, Emission, SegmentMap,
};
use crate::SchemaMeta;
use quillmark_content::serial::from_canonical_value;
use quillmark_core::quill::{CONTENT_MEDIA_TYPE, QUILLMARK_INLINE_KEY};

pub const HELPER_VERSION: &str = "0.1.0";
pub const HELPER_NAMESPACE: &str = "local";
pub const HELPER_NAME: &str = "quillmark-helper";

const LIB_TYP_TEMPLATE: &str = include_str!("lib.typ.template");

/// One generated content block's source map in the produced `lib.typ`: the
/// bracketed `block` range (brackets included) plus the emitter's
/// [`SegmentMap`]s, rebased so every `generated` range indexes `lib.typ`
/// directly. Every glyph the block places carries a span resolving into `block`.
#[derive(Debug)]
pub struct ContentMap {
    pub path: String,
    pub block: Range<usize>,
    pub segments: Vec<SegmentMap>,
    /// [`Emission::declined_images`] for this block: what the field held and the
    /// page will not carry.
    pub declined_images: usize,
}

/// The source plus each content block's [`ContentMap`]. `Err` only when a
/// content exceeds the nesting bound, which import already caps.
pub fn generate_lib_typ(
    data: &serde_json::Value,
    meta: &SchemaMeta,
) -> Result<(String, Vec<ContentMap>), EmitError> {
    let mut cg = Codegen::new(meta);
    let empty = serde_json::Map::new();
    let data_obj = data.as_object().unwrap_or(&empty);
    let data_literal = cg.emit_data(data_obj);
    // The recursive walk returns infallibly and records its failure here.
    if let Some(e) = cg.emit_error.take() {
        return Err(e);
    }
    let display_literal = display_literal(&cg.display);

    // Placeholders are located in the *raw template* (trusted static text), never
    // in already-substituted output, so document data spelling a placeholder
    // cannot hijack a splice point.
    let mut out = String::with_capacity(
        LIB_TYP_TEMPLATE.len() + cg.blocks.len() + data_literal.len() + display_literal.len(),
    );
    let mut cursor = 0usize;
    let mut blocks_at = 0usize;
    for (slot, value) in [
        ("{version}", HELPER_VERSION),
        ("{meta_literal}", meta.meta_literal()),
        ("{content_blocks}", cg.blocks.as_str()),
        ("{data_literal}", data_literal.as_str()),
        ("{display_literal}", display_literal.as_str()),
    ] {
        let rel = LIB_TYP_TEMPLATE[cursor..]
            .find(slot)
            .unwrap_or_else(|| panic!("lib.typ.template carries the {slot} slot in order"));
        let at = cursor + rel;
        out.push_str(&LIB_TYP_TEMPLATE[cursor..at]);
        if slot == "{content_blocks}" {
            blocks_at = out.len();
        }
        out.push_str(value);
        cursor = at + slot.len();
    }
    out.push_str(&LIB_TYP_TEMPLATE[cursor..]);

    // Rebase every recorded window from block-section-relative to
    // `lib.typ`-relative.
    let windows = cg
        .windows
        .into_iter()
        .map(|(path, block, segments, declined_images)| ContentMap {
            path,
            block: (block.start + blocks_at)..(block.end + blocks_at),
            segments: segments
                .into_iter()
                .map(|s| rebase_segment(s, blocks_at))
                .collect(),
            declined_images,
        })
        .collect();
    Ok((out, windows))
}

/// Shifts generated byte offsets only; content (USV) offsets are unaffected.
fn rebase_segment(mut s: SegmentMap, shift: usize) -> SegmentMap {
    s.generated = (s.generated.start + shift)..(s.generated.end + shift);
    for run in &mut s.runs {
        run.1 = (run.1.start + shift)..(run.1.end + shift);
    }
    s
}

/// Accumulates the generated helper across one render.
struct Codegen<'m> {
    meta: &'m SchemaMeta,
    blocks: String,
    windows: Vec<(String, Range<usize>, Vec<SegmentMap>, usize)>,
    counter: usize,
    emit_error: Option<EmitError>,
    /// `(schema address, block binding)` per present date. Backs `_qm-display`.
    display: Vec<(String, String)>,
}

impl<'m> Codegen<'m> {
    fn new(meta: &'m SchemaMeta) -> Self {
        Self {
            meta,
            blocks: String::new(),
            windows: Vec::new(),
            counter: 0,
            emit_error: None,
            display: Vec::new(),
        }
    }

    /// Binds `ec` as a `#let _qm_cN = [\n{markup}\n]` block. The `\n` wrap opens
    /// the block at a line boundary so line-anchored markup parses. Windows are
    /// recorded in `self.blocks` coordinates; `generate_lib_typ` shifts them
    /// once more by the block section's start.
    fn content_block(&mut self, path: &str, ec: Emission) -> String {
        let id = format!("_qm_c{}", self.counter);
        self.counter += 1;
        let declined_images = ec.declined_images;
        self.blocks.push_str("#let ");
        self.blocks.push_str(&id);
        self.blocks.push_str(" = ");
        let start = self.blocks.len();
        self.blocks.push_str("[\n");
        // The emitter's `generated` offsets are relative to the markup body,
        // which opens after `[\n`.
        let markup_at = self.blocks.len();
        self.blocks.push_str(&ec.markup);
        self.blocks.push_str("\n]");
        let end = self.blocks.len();
        self.blocks.push('\n');
        let segments = ec
            .segments
            .into_iter()
            .map(|s| rebase_segment(s, markup_at))
            .collect();
        self.windows
            .push((path.to_string(), start..end, segments, declined_images));
        id
    }

    /// The date sibling of [`content_block`](Self::content_block): a closure
    /// whose `text(..)` body is where the glyphs are born, so they carry this
    /// generated span wherever the plate finally calls it. That is what
    /// `display(addr, ..)` survives laundering on and a native `datetime` does
    /// not, and one block per cell is what gives a card its per-instance region.
    ///
    /// Formatting through the date's own `display` inherits its type, so a
    /// date-only field throws Typst's native `[hour]`-pattern error.
    fn display_block(&mut self, path: &str, constructor: &str) {
        let id = format!("_qm_d{}", self.display.len());
        self.blocks.push_str("#let ");
        self.blocks.push_str(&id);
        self.blocks.push_str(" = (..args) => ");
        // The window covers exactly the `text(..)` call: the node whose span the
        // produced glyphs carry.
        let text_start = self.blocks.len();
        self.blocks.push_str("text(");
        self.blocks.push_str(constructor);
        self.blocks.push_str(".display(..args))");
        let text_end = self.blocks.len();
        self.blocks.push('\n');
        self.windows
            .push((path.to_string(), text_start..text_end, Vec::new(), 0));
        self.display.push((path.to_string(), id));
    }

    /// A date lowers to its **native** `datetime(..)`, so arithmetic,
    /// comparison, components and package interop are ordinary Typst. Blank ⇒
    /// `none`, so `!= none` guards are untouched. A non-blank value that will not
    /// parse raises `backend::invalid_date` from here, the one site that parses,
    /// which is what makes the check total over depth.
    fn date_field(&mut self, path: &str, s: &str, kind: DateKind) -> String {
        match datetime_constructor(s, kind) {
            Some(constructor) => {
                self.display_block(path, &constructor);
                constructor
            }
            None if s.is_empty() => "none".to_string(),
            None => {
                self.emit_error.get_or_insert(EmitError::InvalidDate {
                    field: path.to_string(),
                    value: s.to_string(),
                });
                "none".to_string()
            }
        }
    }

    /// A blank content lowers to `""`, not a block; a value that is not a valid
    /// content (never produced by the seam) degrades to its value literal.
    fn content_field(&mut self, path: &str, value: &serde_json::Value, inline: bool) -> String {
        let emit = if inline {
            emit_content_inline
        } else {
            emit_content
        };
        match from_canonical_value(value) {
            Ok(rt) if !rt.is_blank() => {
                match emit(&rt) {
                    Ok(ec) => self.content_block(path, ec),
                    Err(e) => {
                        self.emit_error.get_or_insert(e);
                        "\"\"".to_string()
                    }
                }
            }
            Ok(_) => "\"\"".to_string(),
            Err(_) => lit(value),
        }
    }

    fn emit_data(&mut self, obj: &serde_json::Map<String, serde_json::Value>) -> String {
        let mut items = Vec::with_capacity(obj.len());
        for (key, value) in sorted(obj) {
            if key == "__meta__" {
                continue;
            }
            if key == "$cards" {
                if let Some(cards) = value.as_array() {
                    items.push(format!("\"$cards\": {}", self.emit_cards(cards)));
                    continue;
                }
            }
            let node = self.meta.field_node(key);
            let expr = self.emit_value(key, node, value);
            items.push(format!("\"{}\": {}", escape_string(key), expr));
        }
        wrap_dict(items)
    }

    /// A card with no string `$kind` passes through as a value literal, assigned
    /// no ordinal or `$path`.
    fn emit_cards(&mut self, cards: &[serde_json::Value]) -> String {
        let mut ordinals: HashMap<String, usize> = HashMap::new();
        let mut out = Vec::with_capacity(cards.len());
        for card in cards {
            let obj = match card.as_object() {
                Some(o) => o,
                None => {
                    out.push(lit(card));
                    continue;
                }
            };
            match obj.get("$kind").and_then(|v| v.as_str()) {
                Some(kind) => {
                    let n = ordinals.entry(kind.to_string()).or_insert(0);
                    let prefix = format!("$cards.{kind}.{n}.");
                    *n += 1;
                    out.push(self.emit_card(obj, kind, &prefix));
                }
                None => out.push(lit(card)),
            }
        }
        wrap_array(out)
    }

    fn emit_card(
        &mut self,
        obj: &serde_json::Map<String, serde_json::Value>,
        kind: &str,
        prefix: &str,
    ) -> String {
        let props = self.meta.card_props(kind);
        let mut items = Vec::with_capacity(obj.len() + 1);
        // The canonical address prefix, so plates compose schema-field addresses
        // without reimplementing the kind+ordinal grammar.
        items.push(format!("\"$path\": \"{}\"", escape_string(prefix)));
        for (key, value) in sorted(obj) {
            if key == "$path" {
                continue;
            }
            let node = props.and_then(|p| p.get(key));
            let expr = self.emit_value(&format!("{prefix}{key}"), node, value);
            items.push(format!("\"{}\": {}", escape_string(key), expr));
        }
        wrap_dict(items)
    }

    /// Lower one value against the schema node that declares it, recursing on
    /// shape: the exact inverse of the walk `field_to_schema` builds the node
    /// with, which is why it cannot be shallower than the schema is.
    ///
    /// `path` is the value's schema address, so every generated projection keys
    /// on an address the recursion produced rather than one reassembled.
    ///
    /// A value whose shape contradicts its declaration reaches here through a
    /// direct `apply`, never the seam, and falls to its literal.
    fn emit_value(
        &mut self,
        path: &str,
        node: Option<&serde_json::Value>,
        value: &serde_json::Value,
    ) -> String {
        match (lowering(node), value) {
            (Lower::Content { inline }, serde_json::Value::Object(_)) => {
                self.content_field(path, value, inline)
            }
            (Lower::Date(kind), serde_json::Value::String(s)) => self.date_field(path, s, kind),
            (Lower::Array(items), serde_json::Value::Array(elems)) => wrap_array(
                elems
                    .iter()
                    .enumerate()
                    .map(|(i, elem)| self.emit_value(&format!("{path}.{i}"), items, elem))
                    .collect(),
            ),
            (Lower::Object(props), serde_json::Value::Object(obj)) => wrap_dict(
                sorted(obj)
                    .into_iter()
                    .map(|(key, elem)| {
                        let expr =
                            self.emit_value(&format!("{path}.{key}"), props.get(key), elem);
                        format!("\"{}\": {}", escape_string(key), expr)
                    })
                    .collect(),
            ),
            _ => lit(value),
        }
    }
}

/// What a schema node lowers to: the codegen walk's whole dispatch.
///
/// A declared type means the same thing wherever it is declared, and every type
/// lowers to its native Typst value unless it has a canonical rendering. Only
/// the content types have one — the authored text — so only they lower to
/// content; a date's rendering is a typographic decision the plate owns, and
/// reaches ink through `display(addr, ..)` instead.
enum Lower<'a> {
    /// `richtext` / `plaintext`, which share everything downstream of this
    /// classification. `inline` lowers to pure inline markup, with no block
    /// terminator to warn inside a paragraph.
    Content { inline: bool },
    Date(DateKind),
    /// The element node, absent where an array declares no `items`.
    Array(Option<&'a serde_json::Value>),
    Object(&'a serde_json::Map<String, serde_json::Value>),
    /// Every other declared type, plus every data key the schema does not
    /// declare and every container declaring no members to recurse on.
    Native,
}

fn lowering(node: Option<&serde_json::Value>) -> Lower<'_> {
    let Some(node) = node else {
        return Lower::Native;
    };
    let str_key = |key: &str| node.get(key).and_then(|v| v.as_str());
    if str_key("contentMediaType") == Some(CONTENT_MEDIA_TYPE) {
        return Lower::Content {
            inline: node.get(QUILLMARK_INLINE_KEY).and_then(|v| v.as_bool()) == Some(true),
        };
    }
    match str_key("format") {
        Some("date") => return Lower::Date(DateKind::Date),
        Some("date-time") => return Lower::Date(DateKind::DateTime),
        _ => {}
    }
    match str_key("type") {
        Some("array") => Lower::Array(node.get("items")),
        // A richtext node is `type: object` too, and the media type claimed it
        // above; what is left here is a typed dictionary or a variant container.
        Some("object") => match node.get("properties").and_then(|v| v.as_object()) {
            Some(props) => Lower::Object(props),
            None => Lower::Native,
        },
        _ => Lower::Native,
    }
}

/// The two date field types, distinguished by their Typst `datetime(..)` arity.
#[derive(Clone, Copy)]
enum DateKind {
    Date,
    DateTime,
}

/// Each present date's `_qm_dN` closure keyed by schema address, backing the
/// `display(field, ..)` helper. Keys sort so a reorder-only `apply` still
/// produces byte-identical source.
fn display_literal(entries: &[(String, String)]) -> String {
    let mut sorted: Vec<&(String, String)> = entries.iter().collect();
    sorted.sort_by(|a, b| a.0.cmp(&b.0));
    wrap_dict(
        sorted
            .into_iter()
            .map(|(path, binding)| format!("\"{}\": {}", escape_string(path), binding))
            .collect(),
    )
}

/// `None` for a string that does not parse (the empty string included), which
/// the caller lowers to `none`. Reuses the coercion layer's own parse, so a
/// value that reached here parses and `None` is the defensive arm.
fn datetime_constructor(s: &str, kind: DateKind) -> Option<String> {
    match kind {
        DateKind::Date => quillmark_core::quill::parse_date(s)
            .map(|(year, month, day)| format!("datetime(year: {year}, month: {month}, day: {day})")),
        DateKind::DateTime => {
            quillmark_core::quill::parse_datetime(s).map(|(year, month, day, hour, minute, second)| {
                format!(
                    "datetime(year: {year}, month: {month}, day: {day}, \
                     hour: {hour}, minute: {minute}, second: {second})"
                )
            })
        }
    }
}

/// Serialize a JSON value as a Typst literal expression, mirroring the value
/// model `json()` produces: `null` ⇒ `none`; integral `i64` numbers ⇒ int
/// literals; all other numbers ⇒ `float("..")` (Typst float *literals* take no
/// exponent syntax, but the `float(str)` constructor parses every finite
/// `f64`, and `json()` rejects non-finite numbers); strings via
/// [`escape_string`]; arrays and objects via [`wrap_array`] / [`wrap_dict`].
pub(crate) fn lit(v: &serde_json::Value) -> String {
    use serde_json::Value::*;
    match v {
        Null => "none".to_string(),
        Bool(b) => b.to_string(),
        Number(n) => {
            if let Some(i) = n.as_i64() {
                // Typst lexes a negative literal as unary `-` over an unsigned
                // magnitude, and `i64::MIN`'s magnitude overflows i64, so it
                // would not round-trip as a literal.
                if i == i64::MIN {
                    "(-9223372036854775807 - 1)".to_string()
                } else {
                    i.to_string()
                }
            } else {
                let f = n.as_f64().expect("json numbers are finite");
                format!("float(\"{f}\")")
            }
        }
        String(s) => format!("\"{}\"", escape_string(s)),
        Array(a) => wrap_array(a.iter().map(lit).collect()),
        Object(o) => wrap_dict(
            sorted(o)
                .into_iter()
                .map(|(k, v)| format!("\"{}\": {}", escape_string(k), lit(v)))
                .collect(),
        ),
    }
}

/// The workspace builds `serde_json` with `preserve_order`, so a map's own
/// iteration order is the caller's. Sorting makes the generated source a pure
/// function of the data's *values*, so a reorder-only `apply` produces
/// byte-identical `lib.typ` and comemo reuses the whole compile.
fn sorted(obj: &serde_json::Map<String, serde_json::Value>) -> Vec<(&String, &serde_json::Value)> {
    let mut entries: Vec<_> = obj.iter().collect();
    entries.sort_by(|a, b| a.0.cmp(b.0));
    entries
}

/// The trailing comma keeps a single element an array rather than a
/// parenthesized scalar.
fn wrap_array(items: Vec<String>) -> String {
    if items.is_empty() {
        "()".to_string()
    } else {
        format!("({},)", items.join(", "))
    }
}

fn wrap_dict(items: Vec<String>) -> String {
    if items.is_empty() {
        "(:)".to_string()
    } else {
        format!("({},)", items.join(", "))
    }
}

pub fn generate_typst_toml() -> String {
    format!(
        r#"[package]
name = "{name}"
version = "{version}"
namespace = "{namespace}"
entrypoint = "lib.typ"
"#,
        name = HELPER_NAME,
        version = HELPER_VERSION,
        namespace = HELPER_NAMESPACE
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::emit::escape_markup;
    use crate::emit::EscapeCtx;
    use quillmark_core::quill::CONTENT_MEDIA_TYPE;

    fn meta_from(schema: serde_json::Value) -> SchemaMeta {
        SchemaMeta::from_schema_json(&schema)
    }

    fn content(markdown: &str) -> serde_json::Value {
        let rt = quillmark_content::import::from_markdown(markdown).expect("import");
        quillmark_content::serial::to_canonical_value(&rt)
    }

    fn richtext_field() -> serde_json::Value {
        serde_json::json!({ "type": "object", "contentMediaType": CONTENT_MEDIA_TYPE })
    }

    fn inline_richtext_field() -> serde_json::Value {
        serde_json::json!({
            "type": "object",
            "contentMediaType": CONTENT_MEDIA_TYPE,
            "quillmark:inline": true
        })
    }

    #[test]
    fn inline_field_lowers_without_parbreak() {
        let meta = meta_from(serde_json::json!({ "properties": {
            "subject": inline_richtext_field(),
            "intro": richtext_field(),
        }}));
        let data = serde_json::json!({
            "subject": content("A **bold** subject"),
            "intro": content("An intro."),
        });
        let (lib, _) = generate_lib_typ(&data, &meta).unwrap();
        assert!(
            lib.contains("[\nA #strong[bold] subject\n]"),
            "inline block should carry no parbreak: {lib}"
        );
        assert!(
            lib.contains("[\nAn intro.\n\n\n]"),
            "block field keeps its terminator: {lib}"
        );
    }

    /// The `quillmark:inline` flag sits on `items` for an array field.
    #[test]
    fn inline_array_lowers_each_element_without_parbreak() {
        let meta = meta_from(serde_json::json!({ "properties": {
            "cc": { "type": "array", "items": inline_richtext_field() }
        }}));
        let data = serde_json::json!({ "cc": [content("First"), content("Second **bold**")] });
        let (lib, _) = generate_lib_typ(&data, &meta).unwrap();
        assert!(lib.contains("[\nFirst\n]"), "{lib}");
        assert!(lib.contains("[\nSecond #strong[bold]\n]"), "{lib}");
    }

    #[test]
    fn content_field_becomes_a_referenced_block_with_a_bracket_window() {
        let meta = meta_from(serde_json::json!({ "properties": { "intro": richtext_field() } }));
        let data = serde_json::json!({ "intro": content("A **bold** intro.") });
        let (lib, windows) = generate_lib_typ(&data, &meta).unwrap();

        let block = "[\nA #strong[bold] intro.\n\n\n]";
        assert!(lib.contains(&format!("#let _qm_c0 = {block}")));
        assert!(lib.contains("\"intro\": _qm_c0"));
        // No eval, no json() blob, no runtime assembly survive.
        assert!(!lib.contains("eval("));
        assert!(!lib.contains("json(bytes"));
        assert!(!lib.contains("insert-content"));
        assert!(!lib.contains("_parse-date"));

        assert_eq!(windows.len(), 1);
        assert_eq!(windows[0].path, "intro");
        assert_eq!(&lib[windows[0].block.clone()], block);
    }

    /// The source map must be byte-accurate against the emitted `lib.typ`, not
    /// just against the emitter's own markup.
    #[test]
    fn segment_maps_index_the_generated_lib_typ() {
        let meta = meta_from(serde_json::json!({ "properties": { "intro": richtext_field() } }));
        let rt = quillmark_content::import::from_markdown("Hello **bold**.\n\nSecond para.")
            .expect("import");
        let data =
            serde_json::json!({ "intro": quillmark_content::serial::to_canonical_value(&rt) });
        let (lib, windows) = generate_lib_typ(&data, &meta).unwrap();

        assert_eq!(windows.len(), 1);
        let cm = &windows[0];
        assert_eq!(cm.segments.len(), 2);
        let chars: Vec<char> = rt.text.chars().collect();
        let mut saw_bold = false;
        for seg in &cm.segments {
            assert!(seg.generated.start <= seg.generated.end && seg.generated.end <= lib.len());
            for (content_range, generated, ctx) in &seg.runs {
                let src: String = chars[content_range.clone()].iter().collect();
                let expect = match ctx {
                    EscapeCtx::Markup => escape_markup(&src),
                    EscapeCtx::StringLit => crate::emit::escape_string(&src),
                };
                assert_eq!(&lib[generated.clone()], expect, "run inverts to its content slice");
                assert!(generated.start >= seg.generated.start && generated.end <= seg.generated.end);
                if src == "bold" {
                    saw_bold = true;
                }
            }
        }
        assert!(saw_bold, "the strong-wrapped run maps back to \"bold\"");
    }

    #[test]
    fn richtext_array_emits_a_block_per_nonblank_element() {
        let meta = meta_from(serde_json::json!({
            "properties": {
                "sections": {
                    "type": "array",
                    "items": richtext_field()
                }
            }
        }));
        let data = serde_json::json!({
            "sections": [content("one"), content(""), content("three")]
        });
        let (lib, windows) = generate_lib_typ(&data, &meta).unwrap();

        let paths: Vec<&str> = windows.iter().map(|w| w.path.as_str()).collect();
        assert_eq!(paths, vec!["sections.0", "sections.2"]);
        assert!(lib.contains("\"sections\": (_qm_c0, \"\", _qm_c1,)"));
    }

    #[test]
    fn date_fields_lower_to_native_datetimes_beside_a_display_projection() {
        let meta = meta_from(serde_json::json!({
            "properties": {
                "issued": { "type": "string", "format": "date" },
                "at": { "type": "string", "format": "date-time" },
                "signed": { "type": "string", "format": "date" }
            }
        }));
        let data = serde_json::json!({
            "issued": "2026-07-03",
            "at": "2026-07-03T09:30",
            "signed": null
        });
        let (lib, windows) = generate_lib_typ(&data, &meta).unwrap();
        // The data cell is the constructor itself: `data.issued.year()` and
        // `data.issued < data.at` are ordinary Typst.
        assert!(
            lib.contains("\"issued\": datetime(year: 2026, month: 7, day: 3)"),
            "{lib}"
        );
        assert!(
            lib.contains(
                "\"at\": datetime(year: 2026, month: 7, day: 3, hour: 9, minute: 30, second: 0)"
            ),
            "{lib}"
        );
        assert!(lib.contains("\"signed\": none"), "{lib}");

        // Keys emit in sorted order, so `_qm_d0` is `at` and `_qm_d1` `issued`.
        assert!(
            lib.contains("#let _qm_d1 = (..args) => text(datetime(year: 2026, month: 7, day: 3).display(..args))"),
            "{lib}"
        );
        assert!(
            lib.contains(r#"("at": _qm_d0, "issued": _qm_d1,)"#),
            "the display table keys by schema address: {lib}"
        );
        let paths: Vec<&str> = windows.iter().map(|w| w.path.as_str()).collect();
        assert!(paths.contains(&"issued"), "{paths:?}");
        assert!(paths.contains(&"at"), "{paths:?}");
        assert!(!paths.contains(&"signed"), "{paths:?}");
    }

    /// Every nested position the one-level nesting contract admits, for both
    /// rich types.
    #[test]
    fn nested_dates_and_content_lower_exactly_as_card_level_ones_do() {
        let meta = meta_from(serde_json::json!({ "properties": {
            "stamps": { "type": "array", "items": { "type": "string", "format": "date" } },
            "contact": { "type": "object", "properties": {
                "reply_by": { "type": "string", "format": "date" },
                "note": richtext_field(),
            }},
            "rows": { "type": "array", "items": { "type": "object", "properties": {
                "on": { "type": "string", "format": "date" },
                "notes": richtext_field(),
            }}},
        }}));
        let data = serde_json::json!({
            "stamps": ["2026-01-02"],
            "contact": { "reply_by": "2026-03-04", "note": content("a **nested** note") },
            "rows": [{ "on": "2026-05-06", "notes": content("row _one_") }],
        });
        let (lib, windows) = generate_lib_typ(&data, &meta).unwrap();

        assert!(
            lib.contains("\"stamps\": (datetime(year: 2026, month: 1, day: 2),)"),
            "an array element is a date: {lib}"
        );
        assert!(
            lib.contains("\"reply_by\": datetime(year: 2026, month: 3, day: 4)"),
            "an object property is a date: {lib}"
        );
        assert!(
            lib.contains("\"on\": datetime(year: 2026, month: 5, day: 6)"),
            "a typed-table row property is a date: {lib}"
        );
        assert!(
            lib.contains("[\na #strong[nested] note\n\n\n]"),
            "an object's content property is a markup block: {lib}"
        );
        assert!(
            lib.contains("[\nrow #emph[one]\n\n\n]"),
            "a row's content property is a markup block: {lib}"
        );
        // No canonical-content wire JSON survives anywhere in the data literal.
        assert!(!lib.contains("\"lines\""), "wire JSON leaked: {lib}");

        // Every projection keys on the address the recursion produced.
        let paths: Vec<&str> = windows.iter().map(|w| w.path.as_str()).collect();
        for expected in ["stamps.0", "contact.reply_by", "contact.note", "rows.0.on", "rows.0.notes"] {
            assert!(paths.contains(&expected), "missing {expected}: {paths:?}");
        }
    }

    /// A bad date must fail loudly at any depth, and must keep its code: a
    /// silent blank would ship a document dated wrong.
    #[test]
    fn an_unparseable_nested_date_is_a_coded_render_error() {
        let meta = meta_from(serde_json::json!({ "properties": {
            "contact": { "type": "object", "properties": {
                "reply_by": { "type": "string", "format": "date" },
            }},
        }}));
        let data = serde_json::json!({ "contact": { "reply_by": "not-a-date" } });
        let err = generate_lib_typ(&data, &meta).expect_err("a bad date stops codegen");
        assert_eq!(err.code(), "backend::invalid_date");
        assert!(err.to_string().contains("contact.reply_by"), "{err}");

        // A blank stays `none`, so a plate's `!= none` guard is untouched.
        let blank = serde_json::json!({ "contact": { "reply_by": "" } });
        let (lib, _) = generate_lib_typ(&blank, &meta).unwrap();
        assert!(lib.contains("\"reply_by\": none"), "{lib}");
    }

    #[test]
    fn cards_carry_path_and_per_kind_ordinals() {
        let meta = meta_from(serde_json::json!({
            "properties": {},
            "$defs": {
                "note_card": {
                    "properties": {
                        "$body": richtext_field(),
                        "on": { "type": "string", "format": "date" }
                    }
                }
            }
        }));
        let data = serde_json::json!({
            "$cards": [
                { "$kind": "note", "$body": content("First body"), "on": "2026-01-02" },
                { "$kind": "note", "$body": content("Second body") }
            ]
        });
        let (lib, windows) = generate_lib_typ(&data, &meta).unwrap();
        // Each instance gets its own windows, keyed by the card's full address.
        let paths: Vec<&str> = windows.iter().map(|w| w.path.as_str()).collect();
        assert!(paths.contains(&"$cards.note.0.$body"), "{paths:?}");
        assert!(paths.contains(&"$cards.note.1.$body"), "{paths:?}");
        assert!(paths.contains(&"$cards.note.0.on"), "{paths:?}");
        assert!(lib.contains("\"$path\": \"$cards.note.0.\""));
        assert!(lib.contains("\"$path\": \"$cards.note.1.\""));
        assert!(
            lib.contains("\"on\": datetime(year: 2026, month: 1, day: 2)"),
            "{lib}"
        );
        assert!(
            lib.contains(r#"("$cards.note.0.on": _qm_d0,)"#),
            "a card date's display projection keys on its per-instance address: {lib}"
        );
    }

    #[test]
    fn meta_literal_carries_the_address_tables() {
        let meta = meta_from(serde_json::json!({
            "properties": {
                "subject": { "type": "string" },
                "refs": { "type": "array", "items": { "type": "string" } }
            }
        }));
        let (lib, _) = generate_lib_typ(&serde_json::json!({}), &meta).unwrap();
        assert!(lib.contains("#let _qm-meta = ("));
        // A scalar is a leaf, and a primitive-element array offers its index
        // step onto one: neither carries a `props` entry.
        assert!(
            lib.contains("\"props\": (\"refs\": (\"item\": (:),), \"subject\": (:),)"),
            "{lib}"
        );
    }

    /// `array_fields` and `object_fields` are one shape, so one predicate reads
    /// both steps.
    #[test]
    fn a_typed_table_row_publishes_its_property_names() {
        let meta = meta_from(serde_json::json!({
            "properties": {
                "tags": { "type": "array", "items": { "type": "string" } },
                "refs": { "type": "array", "items": { "type": "object", "properties": {
                    "org": { "type": "string" },
                    "num": { "type": "string" },
                }}},
            }
        }));
        // A primitive-element array offers the index step and nothing past it.
        let tags = meta.root.resolve("tags.0").expect("tags.0");
        assert!(tags.props.is_empty() && tags.item.is_none());
        assert_eq!(
            meta.root
                .resolve("refs.0")
                .expect("refs.0")
                .props
                .keys()
                .cloned()
                .collect::<Vec<_>>(),
            vec!["num".to_string(), "org".to_string()],
        );
    }

    /// A typed dictionary and a variant container reach the same table: both
    /// project as `type: object` carrying `properties`, the container's `value`
    /// discriminant among them. A richtext field is `type: object` too and must
    /// stay out of it, offering no property step.
    #[test]
    fn object_fields_table_carries_every_declared_container() {
        let meta = meta_from(serde_json::json!({
            "properties": {
                "subject": { "type": "string" },
                "body": richtext_field(),
                "address": { "type": "object", "properties": {
                    "city": { "type": "string" },
                }},
                "classification": { "type": "object", "properties": {
                    "value": { "type": "string", "enum": ["", "CUI"] },
                    "poc": { "type": "string" },
                }},
            },
            "$defs": { "note_card": { "properties": {
                "origin": { "type": "object", "properties": { "office": { "type": "string" } } },
            }}}
        }));
        assert!(meta.root.resolve("address.city").is_some());
        assert!(meta.root.resolve("classification.value").is_some());
        assert!(meta.root.resolve("classification.poc").is_some());
        // A scalar and a richtext field each offer no step.
        assert!(meta.root.resolve("subject.anything").is_none());
        assert!(meta.root.resolve("body.text").is_none());
        assert!(meta.cards["note"].resolve("origin.office").is_some());

        let (lib, _) = generate_lib_typ(&serde_json::json!({}), &meta).unwrap();
        assert!(
            lib.contains("\"cards\": (\"note\": (\"props\": (\"origin\": (\"props\": (\"office\": (:),),),),),)"),
            "{lib}"
        );
    }

    /// A richtext field is `type: object` and would answer the object arm, so
    /// the media type must claim it first — otherwise its wire JSON walks as a
    /// dictionary and reaches the plate as raw canonical content.
    #[test]
    fn a_content_node_is_classified_before_the_object_arm() {
        assert!(matches!(
            lowering(Some(&richtext_field())),
            Lower::Content { inline: false }
        ));
        assert!(matches!(
            lowering(Some(&inline_richtext_field())),
            Lower::Content { inline: true }
        ));
        // An undeclared data key and a scalar take the same arm.
        assert!(matches!(lowering(None), Lower::Native));
        assert!(matches!(
            lowering(Some(&serde_json::json!({ "type": "string" }))),
            Lower::Native
        ));
    }

    /// Slots are located in the raw template only.
    #[test]
    fn data_containing_placeholder_text_cannot_hijack_the_splice() {
        let meta = SchemaMeta::default();
        let data = serde_json::json!({
            "note": "quoting the template: {content_blocks} and {data_literal}"
        });
        let (lib, _) = generate_lib_typ(&data, &meta).unwrap();
        let payload = lib.find("quoting the template").expect("payload present");
        let data_binding = lib.find("#let data =").expect("data binding present");
        assert!(
            payload > data_binding,
            "the payload sits inside the data literal, after the real slot"
        );
    }

    /// A reorder-only `apply` must be a `Source::replace` no-op.
    #[test]
    fn reordered_input_emits_byte_identical_source() {
        let meta = meta_from(serde_json::json!({
            "properties": {
                "body": richtext_field(),
                "note": richtext_field(),
                "issued": { "type": "string", "format": "date" },
                "extra": { "type": "object" }
            },
            "$defs": {
                "note_card": {
                    "properties": {
                        "$body": richtext_field(),
                        "on": { "type": "string", "format": "date" }
                    }
                }
            }
        }));
        let a = serde_json::json!({
            "body": content("The body."),
            "note": content("The note."),
            "issued": "2026-01-02",
            "extra": { "x": 1, "y": 2 },
            "$cards": [ { "$kind": "note", "$body": content("Card body"), "on": "2027-03-04", "tag": "t" } ]
        });
        let b = serde_json::json!({
            "$cards": [ { "tag": "t", "on": "2027-03-04", "$body": content("Card body"), "$kind": "note" } ],
            "extra": { "y": 2, "x": 1 },
            "issued": "2026-01-02",
            "note": content("The note."),
            "body": content("The body.")
        });

        let (lib_a, win_a) = generate_lib_typ(&a, &meta).unwrap();
        let (lib_b, win_b) = generate_lib_typ(&b, &meta).unwrap();
        assert_eq!(lib_a, lib_b, "reordered input must emit identical source");
        let wa: Vec<_> = win_a.iter().map(|w| (&w.path, w.block.clone())).collect();
        let wb: Vec<_> = win_b.iter().map(|w| (&w.path, w.block.clone())).collect();
        assert_eq!(wa, wb, "windows must be identical too");
    }

    #[test]
    fn lit_serializes_the_json_value_model() {
        assert_eq!(lit(&serde_json::json!(null)), "none");
        assert_eq!(lit(&serde_json::json!(true)), "true");
        assert_eq!(lit(&serde_json::json!(42)), "42");
        assert_eq!(
            lit(&serde_json::json!(i64::MIN)),
            "(-9223372036854775807 - 1)"
        );
        assert_eq!(lit(&serde_json::json!(1.5)), "float(\"1.5\")");
        assert_eq!(lit(&serde_json::json!("hi")), "\"hi\"");
        assert_eq!(lit(&serde_json::json!([])), "()");
        assert_eq!(lit(&serde_json::json!([1])), "(1,)");
        assert_eq!(lit(&serde_json::json!({})), "(:)");
        assert_eq!(lit(&serde_json::json!({ "a": 1 })), "(\"a\": 1,)");
    }
}
