"""Type stubs for the compiled `quillmark._quillmark` extension.

Signatures only, hand-kept in step with `src/types.rs` / `src/enums.rs`, which
carry the prose: pyo3 docstrings are runtime-only, so without this file the whole
surface resolves to `Any`.

A `Card` crosses as a plain dict and a payload value as whatever JSON maps to, so
both are `Any`-shaped: their schemas are the quill's, not Python's.
"""

from pathlib import Path
from collections.abc import Sequence
from typing import Any, final

__all__ = [
    "Artifact",
    "CardReader",
    "CardWriter",
    "Diagnostic",
    "Document",
    "Location",
    "OutputFormat",
    "Quill",
    "Quillmark",
    "QuillmarkError",
    "Reader",
    "RenderResult",
    "Severity",
    "Writer",
]

@final
class QuillmarkError(Exception):
    diagnostics: list[Diagnostic]

@final
class Severity:
    ERROR: Severity
    WARNING: Severity

    @property
    def name(self) -> str: ...
    @staticmethod
    def all() -> list[Severity]: ...
    def __repr__(self) -> str: ...

@final
class OutputFormat:
    PDF: OutputFormat
    SVG: OutputFormat
    PNG: OutputFormat

    @property
    def name(self) -> str: ...
    @staticmethod
    def all() -> list[OutputFormat]: ...
    def __repr__(self) -> str: ...

@final
class Location:
    @property
    def file(self) -> str: ...
    @property
    def line(self) -> int: ...
    @property
    def column(self) -> int: ...

@final
class Diagnostic:
    @property
    def severity(self) -> Severity: ...
    @property
    def message(self) -> str: ...
    @property
    def code(self) -> str | None: ...
    @property
    def location(self) -> Location | None: ...
    @property
    def hint(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def source_chain(self) -> list[str]: ...
    @property
    def args(self) -> dict[str, Any]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

@final
class Artifact:
    @property
    def bytes(self) -> bytes: ...
    @property
    def format(self) -> OutputFormat: ...
    @property
    def mime_type(self) -> str: ...
    def save(self, path: str) -> None: ...

@final
class RenderResult:
    @property
    def artifacts(self) -> list[Artifact]: ...
    @property
    def warnings(self) -> list[Diagnostic]: ...
    @property
    def format(self) -> OutputFormat: ...
    @property
    def render_time_ms(self) -> float: ...
    @property
    def regions(self) -> list[dict[str, Any]]: ...

@final
class Document:
    def __new__(cls, quill_ref: str) -> Document: ...
    @staticmethod
    def from_markdown(markdown: str) -> Document: ...
    @staticmethod
    def from_stored(json: str) -> Document: ...
    @staticmethod
    def try_from_stored(json: str) -> Document | None: ...
    @staticmethod
    def storage_version_of(json: str) -> str | None: ...
    @staticmethod
    def current_storage_version() -> str: ...
    @staticmethod
    def format_rules() -> str: ...
    @staticmethod
    def blueprint_instruction(quill_name: str) -> str: ...
    @staticmethod
    def quill_ref_hint() -> str: ...
    @staticmethod
    def make_card(
        kind: str, fields: dict[str, Any] | None = None, body: str | None = None
    ) -> dict[str, Any]: ...
    def to_markdown(self) -> str: ...
    def to_stored(self) -> str: ...
    @property
    def quill_ref(self) -> str: ...
    def set_quill_ref(self, ref_str: str) -> None: ...
    def clone(self) -> Document: ...
    def equals(self, other: Document) -> bool: ...
    def __copy__(self) -> Document: ...
    def __deepcopy__(self, _memo: Any) -> Document: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __repr__(self) -> str: ...
    @property
    def card_count(self) -> int: ...
    @property
    def warnings(self) -> list[Diagnostic]: ...
    @property
    def body(self) -> Any: ...
    @property
    def main(self) -> dict[str, Any]: ...
    @property
    def cards(self) -> list[dict[str, Any]]: ...
    def card(self, index: int) -> dict[str, Any]: ...
    def seed_overlay(self, kind: str) -> Any: ...
    def remove_field(self, name: str, card: int | None = None) -> Any: ...
    def store_ext(self, value: Any, card: int | None = None) -> None: ...
    def remove_ext(self, card: int | None = None) -> Any: ...
    def store_ext_namespace(
        self, namespace: str, value: Any, card: int | None = None
    ) -> None: ...
    def remove_ext_namespace(self, namespace: str, card: int | None = None) -> Any: ...
    def store_seed_overlay(self, card_kind: str, overlay: Any) -> None: ...
    def remove_seed_overlay(self, card_kind: str) -> Any: ...
    def insert_card(self, card: Any, at: int | None = None) -> None: ...
    def remove_card(self, index: int) -> dict[str, Any] | None: ...
    def move_card(self, from_idx: int, to_idx: int) -> None: ...
    def set_card_kind(self, index: int, new_kind: str) -> None: ...

@final
class Quill:
    @staticmethod
    def from_path(path: str | Path) -> Quill: ...
    @property
    def backend_id(self) -> str: ...
    @property
    def warnings(self) -> list[Diagnostic]: ...
    @property
    def quill_ref(self) -> str: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    @property
    def schema(self) -> Any: ...
    @property
    def blueprint(self) -> str: ...
    def writer(self, doc: Document) -> Writer: ...
    def reader(self, doc: Document) -> Reader: ...
    def validate(self, doc: Document) -> list[dict[str, Any]]: ...
    def parse(self, markdown: str) -> Document: ...
    def conform(self, doc: Document) -> list[dict[str, Any]]: ...
    def seed_document(self) -> Document: ...
    def seed_main(self) -> dict[str, Any]: ...
    def seed_card(
        self, card_kind: str, overlay: Any | None = None
    ) -> dict[str, Any] | None: ...

@final
class Writer:
    @property
    def document(self) -> Document: ...
    def set(self, name: str, value: Any) -> None: ...
    def set_all(self, fields: dict[str, Any]) -> None: ...
    def set_values(self, values: dict[str, Any]) -> None: ...
    def revise_body(self, markdown: str) -> None: ...
    def revise_field(self, name: str, text: str) -> None: ...
    def add_card(
        self,
        kind: str,
        fields: dict[str, Any] | None = None,
        body: str | None = None,
        at: int | None = None,
    ) -> None: ...
    def remove_card(self, index: int) -> dict[str, Any] | None: ...
    def card(self, index: int) -> CardWriter: ...

@final
class CardWriter:
    @property
    def index(self) -> int: ...
    @property
    def kind(self) -> str | None: ...
    def set(self, name: str, value: Any) -> None: ...
    def set_all(self, fields: dict[str, Any]) -> None: ...
    def set_values(self, values: dict[str, Any]) -> None: ...
    def revise_body(self, markdown: str) -> None: ...
    def revise_field(self, name: str, text: str) -> None: ...

@final
class Reader:
    @property
    def document(self) -> Document: ...
    def get(self, name: str) -> Any: ...
    def get_content(self, name: str) -> dict[str, Any] | None: ...
    def get_content_at(
        self, name: str, path: Sequence[str | int]
    ) -> dict[str, Any] | None: ...
    def body_markdown(self) -> str: ...
    def values(self) -> dict[str, Any]: ...
    def card(self, index: int) -> CardReader: ...

@final
class CardReader:
    @property
    def index(self) -> int: ...
    @property
    def kind(self) -> str | None: ...
    def get(self, name: str) -> Any: ...
    def get_content(self, name: str) -> dict[str, Any] | None: ...
    def get_content_at(
        self, name: str, path: Sequence[str | int]
    ) -> dict[str, Any] | None: ...
    def body_markdown(self) -> str: ...
    def values(self) -> dict[str, Any]: ...

@final
class Quillmark:
    def __init__(self) -> None: ...
    def render(
        self,
        quill: Quill,
        doc: Document,
        format: OutputFormat | None = None,
        ppi: float | None = None,
        pages: list[int] | None = None,
        regions: bool = False,
    ) -> RenderResult: ...
    def supported_formats(self, quill: Quill) -> list[OutputFormat]: ...
    def registered_backends(self) -> list[str]: ...
