[package]
name = "quillmark-core"
version = "0.1.0"
edition = "2021"
description = "Core types and traits for the quillmark markdown rendering library"
license = "MIT"
repository = "https://github.com/nibsbin/quillmark"

[dependencies]
thiserror = { workspace = true }