#set page(width: 8.5in, height: 11in, margin: 1in)
#set text(font: "NimbusRomNo9L", size: 12pt)

#align(center)[
  #text(size: 16pt, weight: "bold")[Hello Quill Template]
]

#v(1em)


#v(2em)

== Features

This template demonstrates:
- Basic Typst typography
- Content substitution with a markdown placeholder
- Simple page layout with standard margins
- Heading styles

== Usage

1. Place your markdown content in the designated area
2. The quillmark-typst backend will process the markdown
3. Typst will render the final document as PDF or SVG

#v(2em)
#align(center)[
  #text(size: 10pt, style: "italic")[Generated by QuillMark with Typst]
]