// Simple Typst template for QuillMark demonstration
#set page(paper: "us-letter")
#set text(font: "Times New Roman", size: 12pt)

#align(center)[
  #text(size: 16pt, weight: "bold")[{{ title | String }}]
]

#v(1em)

{{ body | Body }}

// This will trigger an error
#invalid_function("unexpected argument")

#v(2em)
#align(right)[
  _Generated by QuillMark_
]