name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ubuntu-latest
          cache-on-failure: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Format check
        run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features: ["", "--all-features", "--no-default-features"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ubuntu-latest
          cache-on-failure: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Tests ${{ matrix.features || 'default features' }}
        run: cargo test --workspace ${{ matrix.features }} --locked

      - name: Doctests ${{ matrix.features || 'default features' }}
        run: cargo test --doc --workspace ${{ matrix.features }} --locked
