name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check (all features)
        run: cargo check --workspace --all-features

      - name: Check (no default features)
        run: cargo check --workspace --no-default-features

      - name: Test
        run: cargo test --workspace --all-features

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Docs build
        run: cargo doc --workspace --no-deps --all-features
