name: CI

on:
  pull_request:
  push:
    tags-ignore:
      - 'v**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0  # Disable incremental compilation for CI (faster clean builds)
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  CARGO_PROFILE_DEV_DEBUG: 0  # Disable debug info in dev builds (much faster)
  CARGO_PROFILE_TEST_DEBUG: 0  # Disable debug info in test builds

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all -- --check

      # TODO: formalize Clippy later
      # - name: Clippy check
      #   run: cargo clippy --all-features --all-targets --locked -- -D warnings

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features: 
          - name: "default"
            flags: ""
          - name: "all-features"
            flags: "--all-features"
          - name: "no-default"
            flags: "--no-default-features"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Tests (${{ matrix.features.name }})
        run: cargo test ${{ matrix.features.flags }} --locked

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build docs
        env:
          RUSTDOCFLAGS: -Dwarnings
        run: cargo doc --no-deps --locked

  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Check WASM build
        run: cargo check --package quillmark-wasm --target wasm32-unknown-unknown --locked

  ci-success:
    runs-on: ubuntu-latest
    needs: [lint, test, docs, wasm]
    if: ${{ always() }}
    steps:
      - name: Fail if any dependency did not succeed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
        run: exit 1