name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ubuntu-latest
          cache-on-failure: true

      - name: Check (no default features)
        run: cargo check --workspace --no-default-features --locked

      - name: Build tests (all features, no run)
        run: cargo test --workspace --all-features --no-run --locked

      - name: Test
        run: cargo test --workspace --all-features --locked

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Docs test
        run: cargo doc --workspace --no-deps --all-features --locked
