name: Publish crates to crates.io

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Publish
    # Only run if CI succeeded or triggered manually/by tag
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ci-${{ hashFiles('**/Cargo.lock') }}"
          cache-on-failure: true

      - name: Publish workspace crates (no verification)
        run: cargo publish --workspace --locked --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Summary
        if: success()
        run: echo "✓ All publishable workspace crates published to crates.io"

      - name: Failure summary
        if: failure()
        run: echo "✗ Publishing failed - check logs above"