name: Publish crates to crates.io

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo-workspaces
        id: cache-workspaces
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-workspaces
          key: ${{ runner.os }}-cargo-workspaces-0.4.1

      - name: Install cargo-workspaces
        if: steps.cache-workspaces.outputs.cache-hit != 'true'
        run: cargo install cargo-workspaces --version 0.4.1

      - name: Show version from tag
        id: version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Publishing version: $VERSION"

      - name: Verify version matches tag
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          CARGO_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.workspace_members[0]' | grep -oP '\d+\.\d+\.\d+')
          if [ "$VERSION" != "$CARGO_VERSION" ]; then
            echo "Error: Tag version ($VERSION) doesn't match Cargo.toml version ($CARGO_VERSION)"
            exit 1
          fi
          echo "✓ Version check passed: $VERSION"

      - name: Publish workspace crates
        run: |
          cargo workspaces publish \
            --from-git \
            --allow-dirty \
            --yes \
            --no-git-push \
            --skip-published
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Summary
        if: success()
        run: |
          echo "✓ Publishing complete!"
          echo "All workspace crates published to crates.io"

      - name: Failure summary
        if: failure()
        run: |
          echo "✗ Publishing failed!"
          echo "Check the logs above for details."