name: Publish crates to crates.io

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # good practice when working with tags

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # Optional: sanity checks before publish
      - name: Show version from tag
        id: version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Releasing version: $VERSION"

      # Publish all changed crates in the right order, waiting for deps as needed
      - name: Publish workspace crates
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          # args passed to `cargo publish`:
          args: --locked
          # helpful toggles:
          ignore-unpublished-changes: true   # exit 0 if nothing needs publishing
          publish-delay: 30000               # extra wait between publishes (ms)

      - name: Output published crates
        if: always()
        run: |
          echo "Published:"
          echo '${{ steps.publish-crates.outputs.published }}'