name: Publish crates to crates.io

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Show version from tag
        id: version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Releasing version: $VERSION"

      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces

      - name: Verify version matches tag
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          CARGO_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          if [ "$VERSION" != "$CARGO_VERSION" ]; then
            echo "Error: Tag version ($VERSION) doesn't match Cargo.toml version ($CARGO_VERSION)"
            exit 1
          fi
          echo "Version check passed: $VERSION"

      - name: Publish workspace crates
        run: |
          cargo workspaces publish \
            --from-git \
            --allow-dirty \
            --yes \
            --no-git-commit \
            --no-git-tag \
            --skip-published
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Summary
        if: success()
        run: |
          echo "✓ Publishing complete!"
          echo "All workspace crates have been published to crates.io"

      - name: Failure summary
        if: failure()
        run: |
          echo "✗ Publishing failed!"
          echo "Check the logs above for details."
          echo "Common issues:"
          echo "  - Version already published (check --skip-published worked)"
          echo "  - Missing CARGO_REGISTRY_TOKEN"
          echo "  - Network issues with crates.io"